import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const defaultThemes = [
  {
    id: 'classic',
    name: 'BRK Classic',
    description: 'Giao diện mặc định của BRK Academy',
    colors: {
      primary: '#f59e0b',
      primaryForeground: '#ffffff',
      secondary: '#0ea5e9',
      secondaryForeground: '#ffffff',
      accent: '#10b981',
      accentForeground: '#ffffff',
      background: '#ffffff',
      backgroundSecondary: '#f8fafc',
      backgroundTertiary: '#f1f5f9',
      foreground: '#0f172a',
      foregroundSecondary: '#475569',
      foregroundMuted: '#94a3b8',
      border: '#e2e8f0',
      borderHover: '#cbd5e1',
      success: '#10b981',
      successForeground: '#ffffff',
      warning: '#f59e0b',
      warningForeground: '#ffffff',
      error: '#ef4444',
      errorForeground: '#ffffff',
      info: '#0ea5e9',
      infoForeground: '#ffffff',
      card: '#ffffff',
      cardForeground: '#0f172a',
      input: '#ffffff',
      inputForeground: '#0f172a',
      ring: '#f59e0b',
      muted: '#f1f5f9',
      mutedForeground: '#94a3b8',
    },
    typography: {
      fontHeading: 'be-vietnam',
      fontBody: 'be-vietnam',
      fontMono: 'source-code',
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.125rem',
      fontSizeXl: '1.25rem',
      fontSize2xl: '1.5rem',
      fontSize3xl: '1.875rem',
      fontSize4xl: '2.25rem',
    },
    layout: {
      radiusSm: '0.125rem',
      radius: '0.25rem',
      radiusMd: '0.375rem',
      radiusLg: '0.5rem',
      radiusXl: '0.75rem',
      radius2xl: '1rem',
      spacingXs: '0.25rem',
      spacingSm: '0.5rem',
      spacing: '1rem',
      spacingMd: '1.5rem',
      spacingLg: '2rem',
      spacingXl: '3rem',
    },
    animations: {
      durationFast: '150ms',
      duration: '200ms',
      durationSlow: '300ms',
      easingDefault: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    effects: {
      gradientPrimary: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
      gradientAccent: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
      blurSm: '4px',
      blur: '8px',
      overlayDark: 'rgba(0, 0, 0, 0.5)',
      glowPrimary: '0 0 20px rgba(245, 158, 11, 0.4)',
    },
    isLocked: true,
    isActive: true,
  },
  {
    id: 'dark',
    name: 'Dark Mode',
    description: 'Giao diện tối chuyên nghiệp',
    colors: {
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      secondary: '#8b5cf6',
      secondaryForeground: '#ffffff',
      accent: '#06b6d4',
      accentForeground: '#ffffff',
      background: '#0f172a',
      backgroundSecondary: '#1e293b',
      backgroundTertiary: '#334155',
      foreground: '#f8fafc',
      foregroundSecondary: '#94a3b8',
      foregroundMuted: '#64748b',
      border: '#334155',
      borderHover: '#475569',
      success: '#22c55e',
      successForeground: '#ffffff',
      warning: '#eab308',
      warningForeground: '#000000',
      error: '#ef4444',
      errorForeground: '#ffffff',
      info: '#38bdf8',
      infoForeground: '#000000',
      card: '#1e293b',
      cardForeground: '#f8fafc',
      input: '#334155',
      inputForeground: '#f8fafc',
      ring: '#3b82f6',
      muted: '#334155',
      mutedForeground: '#64748b',
    },
    typography: {
      fontHeading: 'inter',
      fontBody: 'inter',
      fontMono: 'fira-code',
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.125rem',
      fontSizeXl: '1.25rem',
      fontSize2xl: '1.5rem',
      fontSize3xl: '1.875rem',
      fontSize4xl: '2.25rem',
    },
    layout: {
      radiusSm: '0.125rem',
      radius: '0.25rem',
      radiusMd: '0.375rem',
      radiusLg: '0.5rem',
      radiusXl: '0.75rem',
      radius2xl: '1rem',
      spacingXs: '0.25rem',
      spacingSm: '0.5rem',
      spacing: '1rem',
      spacingMd: '1.5rem',
      spacingLg: '2rem',
      spacingXl: '3rem',
    },
    animations: {
      durationFast: '150ms',
      duration: '200ms',
      durationSlow: '300ms',
      easingDefault: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    effects: {
      gradientPrimary: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
      gradientAccent: 'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
      blurSm: '4px',
      blur: '8px',
      overlayDark: 'rgba(0, 0, 0, 0.7)',
      glowPrimary: '0 0 20px rgba(59, 130, 246, 0.5)',
    },
    isLocked: true,
    isActive: false,
  },
  {
    id: 'light',
    name: 'Light Mode',
    description: 'Giao diện sáng tối giản',
    colors: {
      primary: '#6366f1',
      primaryForeground: '#ffffff',
      secondary: '#ec4899',
      secondaryForeground: '#ffffff',
      accent: '#14b8a6',
      accentForeground: '#ffffff',
      background: '#fafafa',
      backgroundSecondary: '#f4f4f5',
      backgroundTertiary: '#e4e4e7',
      foreground: '#18181b',
      foregroundSecondary: '#71717a',
      foregroundMuted: '#a1a1aa',
      border: '#e4e4e7',
      borderHover: '#d4d4d8',
      success: '#22c55e',
      successForeground: '#ffffff',
      warning: '#eab308',
      warningForeground: '#000000',
      error: '#ef4444',
      errorForeground: '#ffffff',
      info: '#0ea5e9',
      infoForeground: '#ffffff',
      card: '#ffffff',
      cardForeground: '#18181b',
      input: '#ffffff',
      inputForeground: '#18181b',
      ring: '#6366f1',
      muted: '#f4f4f5',
      mutedForeground: '#a1a1aa',
    },
    typography: {
      fontHeading: 'inter',
      fontBody: 'inter',
      fontMono: 'source-code',
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.125rem',
      fontSizeXl: '1.25rem',
      fontSize2xl: '1.5rem',
      fontSize3xl: '1.875rem',
      fontSize4xl: '2.25rem',
    },
    layout: {
      radiusSm: '0.25rem',
      radius: '0.5rem',
      radiusMd: '0.75rem',
      radiusLg: '1rem',
      radiusXl: '1.5rem',
      radius2xl: '2rem',
      spacingXs: '0.25rem',
      spacingSm: '0.5rem',
      spacing: '1rem',
      spacingMd: '1.5rem',
      spacingLg: '2rem',
      spacingXl: '3rem',
    },
    animations: {
      durationFast: '100ms',
      duration: '150ms',
      durationSlow: '200ms',
      easingDefault: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    effects: {
      gradientPrimary: 'linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)',
      gradientAccent: 'linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)',
      blurSm: '2px',
      blur: '4px',
      overlayLight: 'rgba(255, 255, 255, 0.8)',
      glowPrimary: '0 0 15px rgba(99, 102, 241, 0.3)',
    },
    isLocked: true,
    isActive: false,
  },
  {
    id: 'custom-1',
    name: 'Tùy chỉnh 1',
    description: 'Theme tùy chỉnh #1',
    colors: {
      primary: '#8b5cf6',
      primaryForeground: '#ffffff',
      secondary: '#f97316',
      secondaryForeground: '#ffffff',
      accent: '#14b8a6',
      accentForeground: '#ffffff',
      background: '#f8fafc',
      backgroundSecondary: '#f1f5f9',
      backgroundTertiary: '#e2e8f0',
      foreground: '#0f172a',
      foregroundSecondary: '#475569',
      foregroundMuted: '#94a3b8',
      border: '#cbd5e1',
      borderHover: '#94a3b8',
      success: '#22c55e',
      successForeground: '#ffffff',
      warning: '#f59e0b',
      warningForeground: '#ffffff',
      error: '#ef4444',
      errorForeground: '#ffffff',
      info: '#3b82f6',
      infoForeground: '#ffffff',
      card: '#ffffff',
      cardForeground: '#0f172a',
      input: '#ffffff',
      inputForeground: '#0f172a',
      ring: '#8b5cf6',
      muted: '#f1f5f9',
      mutedForeground: '#94a3b8',
    },
    typography: {
      fontHeading: 'poppins',
      fontBody: 'inter',
      fontMono: 'source-code',
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.125rem',
      fontSizeXl: '1.25rem',
      fontSize2xl: '1.5rem',
      fontSize3xl: '1.875rem',
      fontSize4xl: '2.25rem',
    },
    layout: {
      radiusSm: '0.25rem',
      radius: '0.5rem',
      radiusMd: '0.75rem',
      radiusLg: '1rem',
      radiusXl: '1.5rem',
      radius2xl: '2rem',
      spacingXs: '0.25rem',
      spacingSm: '0.5rem',
      spacing: '1rem',
      spacingMd: '1.5rem',
      spacingLg: '2rem',
      spacingXl: '3rem',
    },
    isLocked: false,
    isActive: false,
  },
  {
    id: 'custom-2',
    name: 'Tùy chỉnh 2',
    description: 'Theme tùy chỉnh #2',
    colors: {
      primary: '#0ea5e9',
      primaryForeground: '#ffffff',
      secondary: '#f43f5e',
      secondaryForeground: '#ffffff',
      accent: '#22c55e',
      accentForeground: '#ffffff',
      background: '#ffffff',
      backgroundSecondary: '#f0fdf4',
      backgroundTertiary: '#dcfce7',
      foreground: '#14532d',
      foregroundSecondary: '#166534',
      foregroundMuted: '#22c55e',
      border: '#bbf7d0',
      borderHover: '#86efac',
      success: '#16a34a',
      successForeground: '#ffffff',
      warning: '#ca8a04',
      warningForeground: '#ffffff',
      error: '#dc2626',
      errorForeground: '#ffffff',
      info: '#0284c7',
      infoForeground: '#ffffff',
      card: '#ffffff',
      cardForeground: '#14532d',
      input: '#ffffff',
      inputForeground: '#14532d',
      ring: '#0ea5e9',
      muted: '#f0fdf4',
      mutedForeground: '#22c55e',
    },
    typography: {
      fontHeading: 'be-vietnam',
      fontBody: 'be-vietnam',
      fontMono: 'source-code',
      fontSizeXs: '0.75rem',
      fontSizeSm: '0.875rem',
      fontSizeBase: '1rem',
      fontSizeLg: '1.125rem',
      fontSizeXl: '1.25rem',
      fontSize2xl: '1.5rem',
      fontSize3xl: '1.875rem',
      fontSize4xl: '2.25rem',
    },
    layout: {
      radiusSm: '0.25rem',
      radius: '0.5rem',
      radiusMd: '0.75rem',
      radiusLg: '1rem',
      radiusXl: '1.5rem',
      radius2xl: '2rem',
      spacingXs: '0.25rem',
      spacingSm: '0.5rem',
      spacing: '1rem',
      spacingMd: '1.5rem',
      spacingLg: '2rem',
      spacingXl: '3rem',
    },
    isLocked: false,
    isActive: false,
  },
];

async function main() {
  console.log('Seeding themes...');

  for (const theme of defaultThemes) {
    await prisma.theme.upsert({
      where: { id: theme.id },
      update: theme,
      create: theme,
    });
    console.log(`Upserted theme: ${theme.name}`);
  }

  // Create default site settings if not exists
  const existingSettings = await prisma.siteSettings.findFirst();
  if (!existingSettings) {
    await prisma.siteSettings.create({
      data: {
        id: 'global',
        themeId: 'classic',
        language: 'vi',
      },
    });
    console.log('Created default site settings');
  }

  console.log('Seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
