'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { CRM_STAGES, STAGE_LABELS, CrmOwner, formatCrmDate } from '@/lib/crm/shared'
import type { CrmStageValue } from '@/lib/crm/shared'

const input = 'w-full min-h-11 rounded-xl border bg-white p-3 text-sm'
const button = 'min-h-11 rounded-xl bg-emerald-700 px-4 py-2 text-sm text-white disabled:opacity-50'
async function api<T>(params = '', body?: unknown): Promise<T> {
  const response = await fetch('/api/crm/automation' + params, body ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : { cache: 'no-store' })
  const data = await response.json()
  if (!response.ok) throw new Error(data.error || 'Không xử lý được CRM đợt 3.')
  return data as T
}
type Reports = { from: string; to: string; contacts: number; verifiedPayments: number; verifiedAmount: number; sources: { label: string; count: number }[]; owners: { label: string; count: number }[]; stages: { stage: CrmStageValue; count: number; amount: number }[] }
type Reminders = { tasks: { id: number; contactId: number; title: string; dueAt: string; contact: { name: string } }[]; total: number; today: number; overdue: number; unscheduled: number }
type Settings = { version: number; leadSince: string | null; enrollmentSince: string | null; paymentSince: string | null }
type Segment = { token: string; recipients: { id: number; name: string; email: string }[]; excluded: number }
type Automation = { token: string; rows: { key: string; name: string; title: string; createTask: boolean; dueAt: string }[]; hasMore: boolean }
const money = (value: number) => value.toLocaleString('vi-VN') + ' đ'

export default function CrmPhaseThree({ isAdmin, owners, onChanged, onOpen, onUnscheduled }: { isAdmin: boolean; owners: CrmOwner[]; onChanged: () => void; onOpen: (id: number) => void; onUnscheduled: () => void }) {
  const [mode, setMode] = useState<'reports' | 'reminders' | 'segment' | 'settings'>('reports')
  const [loaded, setLoaded] = useState(false); const [busy, setBusy] = useState(false)
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [campaignId, setCampaignId] = useState<number | null>(null)
  const [from, setFrom] = useState(''); const [to, setTo] = useState('')
  const [reports, setReports] = useState<Reports | null>(null); const [reminders, setReminders] = useState<Reminders | null>(null); const [page, setPage] = useState(1)
  const [source, setSource] = useState(''); const [tag, setTag] = useState(''); const [stage, setStage] = useState(''); const [owner, setOwner] = useState('')
  const [segment, setSegment] = useState<Segment | null>(null); const [title, setTitle] = useState(''); const [subject, setSubject] = useState(''); const [body, setBody] = useState('')
  const [settings, setSettings] = useState<Settings | null>(null); const [lead, setLead] = useState(false); const [enrollment, setEnrollment] = useState(false); const [payment, setPayment] = useState(false)
  const [automation, setAutomation] = useState<Automation | null>(null)
  const run = async (work: () => Promise<void>) => { setBusy(true); setError(''); setNotice(''); try { await work() } catch (e) { setError(e instanceof Error ? e.message : 'Không xử lý được.') } finally { setBusy(false) } }
  const loadReports = async () => { setReports(null); const p = new URLSearchParams({ view: 'reports' }); if (from) p.set('from', from); if (to) p.set('to', to); setReports(await api<Reports>('?' + p)); setLoaded(true) }
  const loadReminders = async (next = 1) => { setReminders(null); setReminders(await api<Reminders>('?view=reminders&page=' + next)); setPage(next) }
  const loadSettings = async () => { setSettings(null); const data = await api<Settings>('?view=settings'); setSettings(data); setLead(!!data.leadSince); setEnrollment(!!data.enrollmentSince); setPayment(!!data.paymentSince); setAutomation(null) }
  const filter = { source, tag, ...(stage ? { stage } : {}), ...(owner ? { ownerId: owner === 'unassigned' ? null : Number(owner) } : {}) }
  return <details className="rounded-2xl border bg-white p-4" onToggle={e => { if (e.currentTarget.open && !loaded && !busy) void run(loadReports) }}><summary className="cursor-pointer font-semibold">Nhắc chăm sóc, nhóm email, tự động hóa & báo cáo</summary><div className="mt-4 space-y-4">
    <div className="flex flex-wrap gap-2">{[['reports', 'Báo cáo'], ['reminders', 'Nhắc chăm sóc'], ...(isAdmin ? [['segment', 'Nhóm email'], ['settings', 'Quy tắc tự động']] : [])].map(([key, label]) => <button key={key} className={button} disabled={busy} aria-pressed={mode === key} onClick={() => { setMode(key as typeof mode); setError(''); setNotice(''); if (key === 'reports') void run(loadReports); if (key === 'reminders') void run(() => loadReminders()); if (key === 'settings') void run(loadSettings) }}>{label}</button>)}</div>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm">{notice}</p>}{busy && <p role="status" className="text-sm">Đang xử lý…</p>}
    {mode === 'reports' && <>
      <form className="grid gap-3 sm:grid-cols-3" onSubmit={e => { e.preventDefault(); void run(loadReports) }}><label className="text-sm">Từ ngày<input disabled={busy} type="date" className={input} value={from} onChange={e => setFrom(e.target.value)} /></label><label className="text-sm">Đến hết ngày<input disabled={busy} type="date" className={input} value={to} onChange={e => setTo(e.target.value)} /></label><button disabled={busy} className={button}>Xem báo cáo</button></form>
      <p className="text-sm text-slate-600">Mặc định 30 ngày, theo giờ Việt Nam. Chỉ tính khách đang chăm sóc trong phạm vi quyền của bạn.</p>
      {reports && <><p className="text-sm">{reports.from} → {reports.to}</p><div className="grid gap-3 sm:grid-cols-3">{[['Khách tạo trong kỳ', reports.contacts], ['Thanh toán đã xác minh trong kỳ', reports.verifiedPayments], ['Tổng tiền đã xác minh', money(reports.verifiedAmount)]].map(([label, value]) => <div key={label} className="rounded-xl bg-emerald-50 p-4"><p className="text-sm">{label}</p><strong className="break-words text-xl">{value}</strong></div>)}</div>
        <div className="grid gap-4 sm:grid-cols-2">{[['Nguồn khách (20 nguồn nhiều nhất)', reports.sources], ['Người phụ trách (tối đa 100)', reports.owners]].map(([label, values]) => <section key={String(label)} className="rounded-xl border p-3"><h3 className="font-semibold">{String(label)}</h3>{(values as Reports['sources']).map((item, i) => <p key={i} className="flex justify-between gap-3 py-2 text-sm"><span className="break-words">{item.label}</span><strong>{item.count}</strong></p>)}</section>)}</div>
        <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="pb-3 text-left">Cơ hội tạo trong kỳ, theo bước tư vấn hiện tại</caption><thead><tr><th className="p-2">Bước</th><th className="p-2">Số cơ hội</th><th className="p-2">Giá trị tư vấn</th></tr></thead><tbody>{CRM_STAGES.map(key => { const row = reports.stages.find(r => r.stage === key); return <tr key={key} className="border-t"><td className="p-2">{STAGE_LABELS[key]}</td><td className="p-2">{row?.count || 0}</td><td className="p-2">{money(row?.amount || 0)}</td></tr> })}</tbody></table></div><p className="text-xs text-slate-500">Giá trị tư vấn không phải tiền đã thu. Báo cáo dùng trạng thái hiện tại, không phải lịch sử chuyển bước. Tiền xác minh chỉ tính tài khoản đã liên kết CRM.</p>
      </>}
    </>}
    {mode === 'reminders' && reminders && <><div className="grid gap-3 sm:grid-cols-3"><p className="rounded-xl bg-amber-50 p-3">Đến hạn hôm nay: <strong>{reminders.today}</strong></p><p className="rounded-xl bg-red-50 p-3">Quá hạn: <strong>{reminders.overdue}</strong></p><button className={button} onClick={onUnscheduled}>Chưa có lịch tiếp theo: {reminders.unscheduled}</button></div><p className="text-xs text-slate-500">Các số hôm nay và quá hạn có thể trùng nhau. Nhắc việc hiển thị trong CRM.</p>
      {reminders.tasks.map(task => <button key={task.id} className="block w-full rounded-xl border p-3 text-left text-sm" onClick={() => onOpen(task.contactId)}><strong>{task.contact.name} · {task.title}</strong><span className="mt-1 block">{formatCrmDate(task.dueAt)}</span></button>)}{!reminders.tasks.length && <p>Không có việc đến hạn.</p>}<div className="flex flex-wrap gap-3"><button disabled={busy || page === 1} className={button} onClick={() => void run(() => loadReminders(page - 1))}>Trước</button><span>{reminders.total} việc · Trang {page}</span><button disabled={busy || page * 20 >= reminders.total} className={button} onClick={() => void run(() => loadReminders(page + 1))}>Sau</button><button disabled={busy} className={button} onClick={() => void run(() => loadReminders(page))}>Làm mới</button></div>
    </>}
    {mode === 'segment' && isAdmin && <><p className="text-sm">Tối đa 500 khách mỗi nháp. Chỉ lấy khách được ghi nhận cho phép nhận email trong hồ sơ; bỏ email bị chặn, khách lưu trữ và địa chỉ trùng. Tạo nháp chưa gửi email.</p>
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Nguồn<input disabled={busy} className={input} value={source} onChange={e => { setSource(e.target.value); setSegment(null) }} /></label><label className="text-sm">Nhãn<input disabled={busy} className={input} value={tag} onChange={e => { setTag(e.target.value); setSegment(null) }} /></label><label className="text-sm">Bước tư vấn<select disabled={busy} className={input} value={stage} onChange={e => { setStage(e.target.value); setSegment(null) }}><option value="">Tất cả</option>{CRM_STAGES.map(key => <option key={key} value={key}>{STAGE_LABELS[key]}</option>)}</select></label><label className="text-sm">Người phụ trách<select disabled={busy} className={input} value={owner} onChange={e => { setOwner(e.target.value); setSegment(null) }}><option value="">Tất cả</option><option value="unassigned">Chưa phân công</option>{owners.map(o => <option key={o.id} value={o.id}>{o.name || o.email}</option>)}</select></label></div>
      <button disabled={busy} className={button} onClick={() => void run(async () => { setSegment(null); setSegment(await api<Segment>('', { action: 'segment.preview', filter })) })}>Xem trước nhóm khách</button>
      {segment && <><p>{segment.recipients.length} người nhận · {segment.excluded} địa chỉ bị chặn hoặc trùng</p><div className="max-h-64 space-y-2 overflow-auto">{segment.recipients.map(r => <p key={r.id} className="break-all text-sm">{r.name} · {r.email}</p>)}</div><p className="text-xs">Danh sách có hiệu lực 15 phút. Nếu hồ sơ thay đổi, cần xem trước lại.</p>
        <form className="space-y-3" onSubmit={e => { e.preventDefault(); void run(async () => { const result = await api<{ campaignId: number }>('', { action: 'campaign.draft', filter, token: segment.token, title, subject, body }); setCampaignId(result.campaignId); setSegment(null); setNotice('Đã tạo chiến dịch nháp. Hãy kiểm tra nội dung và người nhận trong công cụ email trước khi gửi.') }) }}><label className="block text-sm">Tên chiến dịch<input disabled={busy} required maxLength={150} className={input} value={title} onChange={e => setTitle(e.target.value)} /></label><label className="block text-sm">Tiêu đề email<input disabled={busy} required maxLength={200} className={input} value={subject} onChange={e => setSubject(e.target.value)} /></label><label className="block text-sm">Nội dung thuần văn bản<textarea disabled={busy} required rows={5} maxLength={20000} className={input} value={body} onChange={e => setBody(e.target.value)} /></label><button disabled={busy || !segment.recipients.length} className={button}>Xác nhận tạo nháp — chưa gửi</button></form>
      </>}{campaignId != null && <Link className="inline-block min-h-11 py-3 font-semibold text-emerald-800 underline" href={'/tools/email-mkt/' + campaignId}>Mở chiến dịch nháp #{campaignId}</Link>}
    </>}
    {mode === 'settings' && isAdmin && settings && <><p className="text-sm">Quy tắc mặc định tắt. Khi bật, chỉ xét sự kiện mới từ lúc bật. Mỗi sự kiện ghi lịch sử một lần; tạo việc hạn 24 giờ sau sự kiện nếu khách chưa có việc đang mở. Bước tư vấn giữ nguyên.</p>
      <form className="space-y-3" onSubmit={e => { e.preventDefault(); void run(async () => { await api('', { action: 'settings.save', version: settings.version, lead, enrollment, payment }); await loadSettings(); setNotice('Đã lưu quy tắc. Sau khi bản này được triển khai trên nhánh chính, cron hiện có sẽ xử lý mỗi 15 phút.') }) }}>{[['Form đăng ký', lead, setLead], ['Đăng ký khóa mới đang hoạt động', enrollment, setEnrollment], ['Thanh toán mới được xác minh', payment, setPayment]].map(([label, checked, change]) => <label key={String(label)} className="flex min-h-11 items-center gap-3 text-sm"><input disabled={busy} type="checkbox" checked={Boolean(checked)} onChange={e => { (change as (value: boolean) => void)(e.target.checked); setAutomation(null) }} />{String(label)}</label>)}<button disabled={busy} className={button}>Lưu bật / tắt quy tắc</button></form>
      <p className="text-xs text-slate-500">Bản xem trước dùng cấu hình đã lưu. Khi thử trên preview, dùng các nút bên dưới để xử lý; cron chỉ chạy trên SITE_URL của team.</p><button disabled={busy} className={button} onClick={() => void run(async () => { setAutomation(null); setAutomation(await api<Automation>('', { action: 'automation.preview' })) })}>Xem trước tác động — chưa lưu</button>
      {automation && <><p>{automation.rows.length} sự kiện · {automation.rows.filter(r => r.createTask).length} việc mới</p><div className="max-h-64 space-y-2 overflow-auto">{automation.rows.map(row => <p key={row.key} className="rounded-xl border p-3 text-sm">{row.name} · {row.title} · {row.createTask ? 'Tạo việc: ' + formatCrmDate(row.dueAt) : 'Giữ việc đang có'}</p>)}</div>{automation.hasMore && <p className="text-sm">Xử lý tối đa 100 sự kiện/lượt. Xem trước lượt tiếp theo sau khi lưu.</p>}<button disabled={busy || !automation.rows.length} className={button} onClick={() => void run(async () => { const result = await api<{ events: number; tasks: number }>('', { action: 'automation.execute', token: automation.token }); setAutomation(null); setNotice('Đã ghi ' + result.events + ' sự kiện và tạo ' + result.tasks + ' việc.'); onChanged() })}>Xác nhận xử lý các sự kiện này</button></>}
    </>}
  </div></details>
}

export function CrmEmailConsent({ contactId, version, isAdmin, onChanged }: { contactId: number; version: number; isAdmin: boolean; onChanged: () => void }) {
  const [allowed, setAllowed] = useState(false); const [loaded, setLoaded] = useState(false); const [note, setNote] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { let active = true; api<{ marketingEmailAllowed: boolean }>('?view=consent&contactId=' + contactId).then(r => { if (active) { setAllowed(r.marketingEmailAllowed); setLoaded(true) } }).catch(e => { if (active) setError(e.message) }); return () => { active = false } }, [contactId, version])
  return <section className="space-y-3 rounded-2xl border bg-white p-4"><h3 className="font-semibold">Quyền nhận email chăm sóc</h3>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}{loaded && <p className="text-sm">{allowed ? 'Được phép nhận email CRM' : 'Chưa được phép nhận email CRM'}</p>}{isAdmin && loaded && <form className="space-y-3" onSubmit={e => { e.preventDefault(); setBusy(true); setError(''); api('', { action: 'consent.set', contactId, version, allowed, note }).then(onChanged).catch(e => setError(e.message)).finally(() => setBusy(false)) }}><label className="flex min-h-11 items-center gap-3 text-sm"><input disabled={busy} type="checkbox" checked={allowed} onChange={e => setAllowed(e.target.checked)} />Khách cho phép nhận email chăm sóc</label><label className="block text-sm">Ghi nhận cách khách đồng ý / yêu cầu dừng<input disabled={busy} required maxLength={500} className={input} value={note} onChange={e => setNote(e.target.value)} /></label><button disabled={busy} className={button}>Lưu quyền nhận email</button></form>}</section>
}
