export const COUNTRY_CODES = [
    { name: "Việt Nam", code: "+84", iso: "VN", flag: "vn" },
    { name: "Hoa Kỳ", code: "+1", iso: "US", flag: "us" },
    { name: "Canada", code: "+1", iso: "CA", flag: "ca" },
    { name: "Vương quốc Anh", code: "+44", iso: "GB", flag: "gb" },
    { name: "Úc", code: "+61", iso: "AU", flag: "au" },
    { name: "Singapore", code: "+65", iso: "SG", flag: "sg" },
    { name: "Thái Lan", code: "+66", iso: "TH", flag: "th" },
    { name: "Campuchia", code: "+855", iso: "KH", flag: "kh" },
    { name: "Lào", code: "+856", iso: "LA", flag: "la" },
    { name: "Malaysia", code: "+60", iso: "MY", flag: "my" },
    { name: "Indonesia", code: "+62", iso: "ID", flag: "id" },
    { name: "Philippines", code: "+63", iso: "PH", flag: "ph" },
    { name: "Nhật Bản", code: "+81", iso: "JP", flag: "jp" },
    { name: "Hàn Quốc", code: "+82", iso: "KR", flag: "kr" },
    { name: "Trung Quốc", code: "+86", iso: "CN", flag: "cn" },
    { name: "Pháp", code: "+33", iso: "FR", flag: "fr" },
    { name: "Đức", code: "+49", iso: "DE", flag: "de" },
    { name: "Ý", code: "+39", iso: "IT", flag: "it" },
    { name: "Tây Ban Nha", code: "+34", iso: "ES", flag: "es" },
    { name: "Nga", code: "+7", iso: "RU", flag: "ru" },
    { name: "Thụy Sĩ", code: "+41", iso: "CH", flag: "ch" },
    { name: "Thụy Điển", code: "+46", iso: "SE", flag: "se" },
    { name: "Na Uy", code: "+47", iso: "NO", flag: "no" },
    { name: "Đan Mạch", code: "+45", iso: "DK", flag: "dk" },
    { name: "Phần Lan", code: "+358", iso: "FI", flag: "fi" },
    { name: "Hà Lan", code: "+31", iso: "NL", flag: "nl" },
    { name: "Bỉ", code: "+32", iso: "BE", flag: "be" },
    { name: "Áo", code: "+43", iso: "AT", flag: "at" },
    { name: "Bồ Đào Nha", code: "+351", iso: "PT", flag: "pt" },
    { name: "Hy Lạp", code: "+30", iso: "GR", flag: "gr" },
    { name: "Thổ Nhĩ Kỳ", code: "+90", iso: "TR", flag: "tr" },
    { name: "Đài Loan", code: "+886", iso: "TW", flag: "tw" },
    { name: "Hồng Kông", code: "+852", iso: "HK", flag: "hk" },
    { name: "Ma Cao", code: "+853", iso: "MO", flag: "mo" },
    { name: "Ấn Độ", code: "+91", iso: "IN", flag: "in" },
    { name: "Ả Rập Xê Út", code: "+966", iso: "SA", flag: "sa" },
    { name: "UAE (Ả Rập Thống Nhất)", code: "+971", iso: "AE", flag: "ae" },
    { name: "Nam Phi", code: "+27", iso: "ZA", flag: "za" },
    { name: "New Zealand", code: "+64", iso: "NZ", flag: "nz" },
    { name: "Brazil", code: "+55", iso: "BR", flag: "br" },
    { name: "Argentina", code: "+54", iso: "AR", flag: "ar" },
    { name: "Mexico", code: "+52", iso: "MX", flag: "mx" },
    { name: "Israel", code: "+972", iso: "IL", flag: "il" },
    { name: "Afghanistan", code: "+93", iso: "AF", flag: "af" },
    { name: "Albania", code: "+355", iso: "AL", flag: "al" },
    { name: "Algeria", code: "+213", iso: "DZ", flag: "dz" },
    { name: "Andorra", code: "+376", iso: "AD", flag: "ad" },
    { name: "Angola", code: "+244", iso: "AO", flag: "ao" },
    { name: "Armenia", code: "+374", iso: "AM", flag: "am" },
    { name: "Azerbaijan", code: "+994", iso: "AZ", flag: "az" },
    { name: "Bahamas", code: "+1242", iso: "BS", flag: "bs" },
    { name: "Bahrain", code: "+973", iso: "BH", flag: "bh" },
    { name: "Bangladesh", code: "+880", iso: "BD", flag: "bd" },
    { name: "Barbados", code: "+1246", iso: "BB", flag: "bb" },
    { name: "Belarus", code: "+375", iso: "BY", flag: "by" },
    { name: "Belize", code: "+501", iso: "BZ", flag: "bz" },
    { name: "Benin", code: "+229", iso: "BJ", flag: "bj" },
    { name: "Bhutan", code: "+975", iso: "BT", flag: "bt" },
    { name: "Bolivia", code: "+591", iso: "BO", flag: "bo" },
    { name: "Bosnia và Herzegovina", code: "+387", iso: "BA", flag: "ba" },
    { name: "Botswana", code: "+267", iso: "BW", flag: "bw" },
    { name: "Brunei", code: "+673", iso: "BN", flag: "bn" },
    { name: "Bulgaria", code: "+359", iso: "BG", flag: "bg" },
    { name: "Burkina Faso", code: "+226", iso: "BF", flag: "bf" },
    { name: "Burundi", code: "+257", iso: "BI", flag: "bi" },
    { name: "Cameroon", code: "+237", iso: "CM", flag: "cm" },
    { name: "Cape Verde", code: "+238", iso: "CV", flag: "cv" },
    { name: "Trung Phi", code: "+236", iso: "CF", flag: "cf" },
    { name: "Chad", code: "+235", iso: "TD", flag: "td" },
    { name: "Chile", code: "+56", iso: "CL", flag: "cl" },
    { name: "Colombia", code: "+57", iso: "CO", flag: "co" },
    { name: "Comoros", code: "+269", iso: "KM", flag: "km" },
    { name: "Congo", code: "+242", iso: "CG", flag: "cg" },
    { name: "Cộng hòa Dân chủ Congo", code: "+243", iso: "CD", flag: "cd" },
    { name: "Costa Rica", code: "+506", iso: "CR", flag: "cr" },
    { name: "Croatia", code: "+385", iso: "HR", flag: "hr" },
    { name: "Cuba", code: "+53", iso: "CU", flag: "cu" },
    { name: "Síp", code: "+357", iso: "CY", flag: "cy" },
    { name: "Cộng hòa Séc", code: "+420", iso: "CZ", flag: "cz" },
    { name: "Djibouti", code: "+253", iso: "DJ", flag: "dj" },
    { name: "Dominica", code: "+1767", iso: "DM", flag: "dm" },
    { name: "Cộng hòa Dominica", code: "+1849", iso: "DO", flag: "do" },
    { name: "Ecuador", code: "+593", iso: "EC", flag: "ec" },
    { name: "Ai Cập", code: "+20", iso: "EG", flag: "eg" },
    { name: "El Salvador", code: "+503", iso: "SV", flag: "sv" },
    { name: "Guinea Xích đạo", code: "+240", iso: "GQ", flag: "gq" },
    { name: "Eritrea", code: "+291", iso: "ER", flag: "er" },
    { name: "Estonia", code: "+372", iso: "EE", flag: "ee" },
    { name: "Ethiopia", code: "+251", iso: "ET", flag: "et" },
    { name: "Fiji", code: "+679", iso: "FJ", flag: "fj" },
    { name: "Gabon", code: "+241", iso: "GA", flag: "ga" },
    { name: "Gambia", code: "+220", iso: "GM", flag: "gm" },
    { name: "Georgia", code: "+995", iso: "GE", flag: "ge" },
    { name: "Ghana", code: "+233", iso: "GH", flag: "gh" },
    { name: "Grenada", code: "+1473", iso: "GD", flag: "gd" },
    { name: "Guatemala", code: "+502", iso: "GT", flag: "gt" },
    { name: "Guinea", code: "+224", iso: "GN", flag: "gn" },
    { name: "Guinea-Bissau", code: "+245", iso: "GW", flag: "gw" },
    { name: "Guyana", code: "+595", iso: "GY", flag: "gy" },
    { name: "Haiti", code: "+509", iso: "HT", flag: "ht" },
    { name: "Honduras", code: "+504", iso: "HN", flag: "hn" },
    { name: "Hungary", code: "+36", iso: "HU", flag: "hu" },
    { name: "Iceland", code: "+354", iso: "IS", flag: "is" },
    { name: "Iran", code: "+98", iso: "IR", flag: "ir" },
    { name: "Iraq", code: "+964", iso: "IQ", flag: "iq" },
    { name: "Ireland", code: "+353", iso: "IE", flag: "ie" },
    { name: "Jamaica", code: "+1876", iso: "JM", flag: "jm" },
    { name: "Jordan", code: "+962", iso: "JO", flag: "jo" },
    { name: "Kazakhstan", code: "+77", iso: "KZ", flag: "kz" },
    { name: "Kenya", code: "+254", iso: "KE", flag: "ke" },
    { name: "Kuwait", code: "+965", iso: "KW", flag: "kw" },
    { name: "Kyrgyzstan", code: "+996", iso: "KG", flag: "kg" },
    { name: "Latvia", code: "+371", iso: "LV", flag: "lv" },
    { name: "Lebanon", code: "+961", iso: "LB", flag: "lb" },
    { name: "Lesotho", code: "+266", iso: "LS", flag: "ls" },
    { name: "Liberia", code: "+231", iso: "LR", flag: "lr" },
    { name: "Libya", code: "+218", iso: "LY", flag: "ly" },
    { name: "Liechtenstein", code: "+423", iso: "LI", flag: "li" },
    { name: "Lithuania", code: "+370", iso: "LT", flag: "lt" },
    { name: "Luxembourg", code: "+352", iso: "LU", flag: "lu" },
    { name: "Madagascar", code: "+261", iso: "MG", flag: "mg" },
    { name: "Malawi", code: "+265", iso: "MW", flag: "mw" },
    { name: "Maldives", code: "+960", iso: "MV", flag: "mv" },
    { name: "Mali", code: "+223", iso: "ML", flag: "ml" },
    { name: "Malta", code: "+356", iso: "MT", flag: "mt" },
    { name: "Mauritania", code: "+222", iso: "MR", flag: "mr" },
    { name: "Mauritius", code: "+230", iso: "MU", flag: "mu" },
    { name: "Moldova", code: "+373", iso: "MD", flag: "md" },
    { name: "Monaco", code: "+377", iso: "MC", flag: "mc" },
    { name: "Mông Cổ", code: "+976", iso: "MN", flag: "mn" },
    { name: "Montenegro", code: "+382", iso: "ME", flag: "me" },
    { name: "Ma-rốc", code: "+212", iso: "MA", flag: "ma" },
    { name: "Mozambique", code: "+258", iso: "MZ", flag: "mz" },
    { name: "Myanmar", code: "+95", iso: "MM", flag: "mm" },
    { name: "Namibia", code: "+264", iso: "NA", flag: "na" },
    { name: "Nepal", code: "+977", iso: "NP", flag: "np" },
    { name: "Nicaragua", code: "+505", iso: "NI", flag: "ni" },
    { name: "Niger", code: "+227", iso: "NE", flag: "ne" },
    { name: "Nigeria", code: "+234", iso: "NG", flag: "ng" },
    { name: "Oman", code: "+968", iso: "OM", flag: "om" },
    { name: "Pakistan", code: "+92", iso: "PK", flag: "pk" },
    { name: "Panama", code: "+507", iso: "PA", flag: "pa" },
    { name: "Papua New Guinea", code: "+675", iso: "PG", flag: "pg" },
    { name: "Paraguay", code: "+595", iso: "PY", flag: "py" },
    { name: "Peru", code: "+51", iso: "PE", flag: "pe" },
    { name: "Ba Lan", code: "+48", iso: "PL", flag: "pl" },
    { name: "Qatar", code: "+974", iso: "QA", flag: "qa" },
    { name: "Romania", code: "+40", iso: "RO", flag: "ro" },
    { name: "Rwanda", code: "+250", iso: "RW", flag: "rw" },
    { name: "Samoa", code: "+685", iso: "WS", flag: "ws" },
    { name: "San Marino", code: "+378", iso: "SM", flag: "sm" },
    { name: "Senegal", code: "+221", iso: "SN", flag: "sn" },
    { name: "Serbia", code: "+381", iso: "RS", flag: "rs" },
    { name: "Seychelles", code: "+248", iso: "SC", flag: "sc" },
    { name: "Sierra Leone", code: "+232", iso: "SL", flag: "sl" },
    { name: "Slovakia", code: "+421", iso: "SK", flag: "sk" },
    { name: "Slovenia", code: "+386", iso: "SI", flag: "si" },
    { name: "Somalia", code: "+252", iso: "SO", flag: "so" },
    { name: "Nam Sudan", code: "+211", iso: "SS", flag: "ss" },
    { name: "Sri Lanka", code: "+94", iso: "LK", flag: "lk" },
    { name: "Sudan", code: "+249", iso: "SD", flag: "sd" },
    { name: "Suriname", code: "+597", iso: "SR", flag: "sr" },
    { name: "Syria", code: "+963", iso: "SY", flag: "sy" },
    { name: "Tajikistan", code: "+992", iso: "TJ", flag: "tj" },
    { name: "Tanzania", code: "+255", iso: "TZ", flag: "tz" },
    { name: "Togo", code: "+228", iso: "TG", flag: "tg" },
    { name: "Tonga", code: "+676", iso: "TO", flag: "to" },
    { name: "Trinidad và Tobago", code: "+1868", iso: "TT", flag: "tt" },
    { name: "Tunisia", code: "+216", iso: "TN", flag: "tn" },
    { name: "Turkmenistan", code: "+993", iso: "TM", flag: "tm" },
    { name: "Uganda", code: "+256", iso: "UG", flag: "ug" },
    { name: "Ukraine", code: "+380", iso: "UA", flag: "ua" },
    { name: "Uruguay", code: "+598", iso: "UY", flag: "uy" },
    { name: "Uzbekistan", code: "+998", iso: "UZ", flag: "uz" },
    { name: "Vanuatu", code: "+678", iso: "VU", flag: "vu" },
    { name: "Venezuela", code: "+58", iso: "VE", flag: "ve" },
    { name: "Yemen", code: "+967", iso: "YE", flag: "ye" },
    { name: "Zambia", code: "+260", iso: "ZM", flag: "zm" },
    { name: "Zimbabwe", code: "+263", iso: "ZW", flag: "zw" }
];
