'use client'
/* eslint-disable @next/next/no-html-link-for-pages -- Rời cấu hình để tải lại trạng thái website từ máy chủ. */
import {useEffect,useState} from 'react'

type Domain={hostname:string;token:string;enabled:boolean;verifiedAt:string|null;message:string;courses:boolean;crm:boolean;affiliate:boolean}
export default function DomainManager() {
  const [domains,setDomains]=useState<Domain[]>([]),[hostname,setHostname]=useState('brk.io.vn'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false)
  const endpoint='/api/websites/domains'
  useEffect(()=>{ const abort=new AbortController(); fetch(endpoint,{signal:abort.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setDomains(data.domains);setLoaded(true)}).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort() },[])
  async function submit(command:Record<string,unknown>) {
    setBusy(true);setError('')
    try {const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});const data=await r.json();if(!r.ok)throw new Error(data.error);setDomains(data.domains)} catch(e) {setError(e instanceof Error ? e.message : 'Không thể xử lý tên miền.')} finally {setBusy(false)}
  }
  return <main className="max-w-4xl mx-auto p-4 sm:p-8 grid gap-6"><a href="/tools/my-site/manage" className="underline">← Quản lý website</a><h1 className="text-2xl font-bold">Tên miền riêng</h1><p>Tên miền hiển thị website đã xuất bản. Dữ liệu vẫn lưu trong Giautoandien. Custom domain đang thử nghiệm cho quản trị viên.</p>{error && <p role="alert" className="bg-red-50 text-red-800 p-4 rounded-xl">{error}</p>}<fieldset disabled={busy || !loaded} className="grid gap-6"><form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();void submit({action:'add',hostname})}}><label className="flex-1 min-w-0">Tên miền<input className="border rounded-lg p-3 w-full" placeholder="tenmien.vn" value={hostname} onChange={e=>setHostname(e.target.value)} required /></label><button className="border rounded-lg p-3 self-end">Thêm tên miền</button></form>{domains.map(d=><section key={d.hostname} className="border rounded-2xl p-4 sm:p-6 grid gap-4"><h2 className="font-bold text-xl break-all">{d.hostname}</h2><p className={d.enabled ? 'text-green-700' : 'text-amber-800'}>{d.enabled ? 'Đang hoạt động' : 'Chưa hoạt động'} · {d.message}</p><ol className="list-decimal pl-5 grid gap-3"><li>Vào Vercel → dự án hocvienbrk → Settings → Domains → thêm <strong>{d.hostname}</strong>. Khi thử nghiệm, chọn Preview và đúng nhánh feat/custom-domains; khi chạy chính thức, chọn Production. Gắn trực tiếp, không chuyển hướng.</li><li>Tại nơi quản lý DNS, nhập bản ghi A/CNAME đúng giá trị Vercel hiển thị. Giữ nguyên các bản ghi email đang dùng.</li><li>Thêm bản ghi TXT xác minh bên dưới. Nếu dùng Cloudflare, để DNS only trong lúc xác minh.</li><li>Chờ Vercel báo DNS và HTTPS hợp lệ, sau đó bấm “Kiểm tra và kích hoạt”.</li></ol><div className="bg-slate-50 rounded-xl p-3 grid gap-2 text-sm"><p>Loại: <strong>TXT</strong></p><p>Tên đầy đủ: <code className="break-all select-all">_giautoandien.{d.hostname}</code></p><p>Giá trị: <code className="break-all select-all">gau-domain={d.token}</code></p></div><p className="text-sm">Với DNS zone của {d.hostname}, ô tên thường chỉ nhập <code>_giautoandien</code>. Mỗi tên miền cần bản ghi riêng.</p><a className="text-violet-700 underline" href="/tools/my-site/manage">Quản lý chức năng và gói cơ bản →</a><div className="flex flex-wrap gap-3"><button className="bg-violet-600 text-white rounded-lg p-3" onClick={()=>void submit({action:'check',hostname:d.hostname})}>{busy ? 'Đang xử lý…' : 'Kiểm tra và kích hoạt'}</button>{d.enabled && <a href={'https://'+d.hostname} target="_blank" rel="noreferrer" className="border rounded-lg p-3">Mở website</a>}<button className="border rounded-lg p-3" onClick={()=>void submit({action:'disable',hostname:d.hostname})}>Tạm dừng</button><button className="border rounded-lg p-3 text-red-700" onClick={()=>{if(window.confirm('Gỡ tên miền khỏi website? DNS và Vercel cần gỡ riêng.'))void submit({action:'remove',hostname:d.hostname})}}>Gỡ tên miền</button></div></section>)}</fieldset></main>
}
