'use client'
/* eslint-disable @next/next/no-html-link-for-pages -- Independent management tool. */
import {useMemo} from 'react'
import type {FormBinding,ManagedForm} from '@/lib/crm/form-shared'
import {inspectTemplateForms} from '@/lib/website/page-forms'

export default function TemplateFormBindings({html,forms,bindings,onChange,disabled,regions}:{html:string;forms:ManagedForm[];bindings:FormBinding[];onChange:(value:FormBinding[])=>void;disabled:boolean;regions:{id:string;label:string}[]}){
  const detected=useMemo(()=>inspectTemplateForms(html),[html]),available=forms.filter(f=>f.active)
  const input='mt-1 w-full rounded-xl border bg-white p-3 text-sm'
  const update=(index:number,value:FormBinding)=>onChange(bindings.map((b,i)=>i===index?value:b))
  return <section className="space-y-3 rounded-xl border border-violet-200 bg-violet-50 p-4">
    <div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">Kết nối form đăng ký → CRM của tôi</h2><p className="mt-1 text-sm text-slate-600">{detected.length} form được tìm thấy trong template. Chọn form hệ thống rồi ghép các ô một lần.</p></div><a href="/tools/my-site/forms" className="text-sm text-violet-700 underline">Tạo / sửa form của tôi ↗</a></div>
    {!available.length && <p className="text-sm">Tạo một form đang nhận đăng ký trước khi kết nối.</p>}<p className="text-xs text-slate-500">Khi dùng tên miền riêng, hãy bật kết nối CRM tại Quản lý website → Ứng dụng & quyền truy cập.</p>
    <fieldset disabled={disabled} className="space-y-3">{bindings.map((binding,index)=>{
      const definition=forms.find(f=>f.id===binding.formId),original=binding.mode==='existing'?detected.find(f=>f.index===binding.index):null
      return <details key={index} open className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-medium">{index+1}. {definition?.name || 'Form không còn khả dụng'} · {binding.mode==='existing'?'Giữ giao diện gốc':'Chèn form hệ thống'}</summary><div className="mt-3 space-y-3">
        <label className="block text-sm">Đưa đăng ký vào form<select className={input} value={binding.formId} onChange={e=>update(index,binding.mode==='existing'?{...binding,formId:e.target.value,mapping:{}}:{...binding,formId:e.target.value})}>{!available.some(f=>f.id===binding.formId) && <option value={binding.formId}>Form đã tắt / không tồn tại</option>}{available.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>
        {binding.mode==='existing'?<>
          <label className="block text-sm">Form trong template<select className={input} value={binding.index} onChange={e=>update(index,{...binding,index:Number(e.target.value),mapping:{}})}>{detected.map(f=><option key={f.index} value={f.index}>{f.label}</option>)}</select></label>
          <p className="text-xs text-slate-500">Chọn ô tương ứng với từng câu hỏi. Nếu template dùng nhóm radio / checkbox, giữ Ctrl hoặc ⌘ để chọn tất cả ô của nhóm và đặt đáp án form trùng với giá trị của nhóm. Ô chọn danh sách sẽ dùng các lựa chọn của form hệ thống. Trường tùy chọn có thể bỏ qua.</p>
          <div className="grid gap-3 sm:grid-cols-2">{definition?.config.fields.map(field=><label key={field.id} className="block text-sm">{field.label}{field.required?' *':''}<select aria-label={'Ghép '+field.label} multiple className={input} size={Math.min(4,(original?.controls.length || 0)+1)} value={(binding.mapping[field.id] || []).map(String)} onChange={e=>{const values=Array.from(e.target.selectedOptions).map(o=>Number(o.value)).filter(n=>n>=0);const mapping={...binding.mapping};if(values.length)mapping[field.id]=values;else delete mapping[field.id];update(index,{...binding,mapping})}}><option value="-1">Không ghép ô</option>{original?.controls.map(control=><option key={control.index} value={control.index}>{control.index+1}. {control.label} ({control.type}){control.values.length?' · '+control.values.join(', '):''}</option>)}</select></label>)}</div>
        </>:<div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Chèn thêm vào vùng<select className={input} value={binding.region} onChange={e=>update(index,{...binding,region:e.target.value})}><option value="__append__">Cuối trang</option>{regions.filter(r=>r.id!=='courses' && r.id!=='course-list').map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label><label className="block text-sm">Giao diện form<select className={input} value={binding.theme} onChange={e=>update(index,{...binding,theme:e.target.value as 'light'|'dark'})}><option value="light">Nền sáng</option><option value="dark">Nền tối</option></select></label></div>}
        <button type="button" className="rounded-lg border px-3 py-2 text-sm text-red-700" onClick={()=>onChange(bindings.filter((_,i)=>i!==index))}>Gỡ kết nối này</button>
      </div></details>
    })}<div className="flex flex-wrap gap-2"><button type="button" className="rounded-xl border bg-white px-3 py-2 text-sm disabled:opacity-50" disabled={!available.length || !detected.length || bindings.length>=10} onClick={()=>onChange([...bindings,{mode:'existing',formId:available[0].id,index:detected.find(f=>!bindings.some(b=>b.mode==='existing' && b.index===f.index))?.index ?? detected[0].index,mapping:{}}])}>+ Kết nối form có sẵn</button><button type="button" className="rounded-xl border bg-white px-3 py-2 text-sm disabled:opacity-50" disabled={!available.length || bindings.length>=10} onClick={()=>onChange([...bindings,{mode:'generated',formId:available[0].id,region:'__append__',theme:'light'}])}>+ Chèn form hệ thống</button></div></fieldset>
  </section>
}
