'use client'

import type { WebsiteData } from './WebsiteView'

const gold='#d9ad42'
const serif="Georgia, 'Times New Roman', serif"
const imgs={
 founder:'https://lh3.googleusercontent.com/d/18xXBR6HfEX5mMrJ7xI6YKP0Az01ST5X5',
 who:'https://lh3.googleusercontent.com/d/11jCgpbg3fKfayhKZxfZqYPiVOrik85KQ',
 foundations:'https://lh3.googleusercontent.com/d/174m80UAa1q3d_vyG8QjTuvx9d_W8Yhp-',
 community:'https://lh3.googleusercontent.com/d/1gExIBj-I7cgD_GJ5q1tUyMUWQsuWeZvJ'
}
function Lotus({small=false}:{small?:boolean}){return <svg viewBox="0 0 120 90" aria-hidden="true" className={small?'h-10 w-14':'h-20 w-28'}><g fill="none" stroke="#e8c968" strokeWidth="2"><path d="M60 72C42 57 38 37 60 9c22 28 18 48 0 63Z"/><path d="M58 72C35 67 21 51 23 26c23 9 34 25 35 46Z"/><path d="M62 72c23-5 37-21 35-46-23 9-34 25-35 46Z"/><path d="M48 74C27 76 12 66 7 48c21 0 34 9 41 26Z"/><path d="M72 74c21 2 36-8 41-26-21 0-34 9-41 26Z"/><path d="M26 79h68"/></g></svg>}
function Ornament(){return <div className="flex items-center justify-center gap-3 my-5 opacity-80"><i className="h-px w-20 bg-gradient-to-r from-transparent to-[#d9ad42]"/><span className="text-[#d9ad42]">✦</span><i className="h-px w-20 bg-gradient-to-l from-transparent to-[#d9ad42]"/></div>}
function Arch({title,children,tone,icon='✦'}:{title:string;children:React.ReactNode;tone:string;icon?:string}){return <div className="group relative overflow-hidden rounded-t-[120px] rounded-b-[26px] border border-[#d9ad42]/60 p-5 pt-16 text-center min-h-[430px] shadow-[0_20px_70px_rgba(0,0,0,.35)]" style={{background:`radial-gradient(circle at 50% 10%,${tone},#07101b 68%)`}}><div className="absolute inset-3 rounded-t-[108px] rounded-b-[20px] border border-[#e8c968]/20"/><div className="absolute inset-x-0 top-0 h-28 bg-gradient-to-b from-[#e8c968]/10 to-transparent"/><div className="relative"><div className="mx-auto mb-5 grid h-20 w-20 place-items-center rounded-full border border-[#e8c968]/70 bg-black/20 text-4xl text-[#f4cf62] shadow-[0_0_28px_rgba(218,175,55,.25)]">{icon}</div><h3 className="text-2xl font-bold text-[#f1ca55]" style={{fontFamily:serif}}>{title}</h3><Ornament/><div className="mx-auto max-w-[290px] whitespace-pre-line rounded-2xl bg-[#f7e8bd] px-5 py-6 leading-8 text-[#16120a] shadow-inner">{children}</div><div className="mx-auto mt-6 w-fit rounded-full border border-[#e8c968]/55 px-5 py-2 text-xs font-bold tracking-wider text-[#f1ca55]">KHÁM PHÁ NGAY →</div></div></div>}
function SectionTitle({eyebrow,title,dark=false}:{eyebrow?:string;title:string;dark?:boolean}){return <div className="mx-auto mb-10 max-w-4xl text-center">{eyebrow&&<div className="mb-3 text-xs font-bold tracking-[.35em] text-[#d9ad42]">{eyebrow}</div>}<h2 className={"text-3xl font-bold tracking-wide md:text-5xl "+(dark?'text-[#35250c]':'text-[#e8c968]')} style={{fontFamily:serif}}>{title}</h2><Ornament/></div>}
function TopNav({slug}:{slug:string}){return <header className="sticky top-0 z-30 border-b border-[#d9ad42]/20 bg-[#050a12]/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href={'/page/'+slug} className="flex items-center gap-2 text-xl font-bold text-[#e8c968]" style={{fontFamily:serif}}><Lotus small/><span>THE TOP 1%</span></a><nav className="hidden gap-7 text-sm text-[#f4ead2]/80 md:flex"><a href={'/page/'+slug}>Trang chủ</a><a href="#about">Về The Top 1%</a><a href="#programs">Khóa học</a><a href="#community">Cộng đồng</a></nav><a href="#journey" className="rounded-full border border-[#d9ad42]/70 px-5 py-2 text-sm font-bold text-[#e8c968]">Khám phá</a></div></header>}
export default function TheTopSite({data,slug,pageSlug='',preview=false}:{data:WebsiteData;slug:string;pageSlug?:string;preview?:boolean}){
 if(pageSlug==='khoa-hoc'||pageSlug==='chuong-trinh') return <div className="min-h-screen bg-[#060b14] text-[#f4ead2]"><TopNav slug={slug}/><main className="mx-auto max-w-7xl px-5 py-16"><SectionTitle eyebrow="THE TOP 1% ACADEMY" title="CÁC KHÓA HỌC & CHƯƠNG TRÌNH"/><div className="grid gap-6 md:grid-cols-3">{data.courses.map(c=><a key={c.id} href={preview?'#':c.href} className="overflow-hidden rounded-3xl border border-[#d9ad42]/25 bg-[#0c1524]"><div className="aspect-[4/3] bg-[#101b2d]">{c.image&&<img src={c.image} alt="" className="h-full w-full object-cover"/>}</div><div className="p-6"><h3 className=" text-xl font-bold text-[#e8c968]">{c.title}</h3><p className="mt-3 line-clamp-4 text-sm leading-6 text-[#f4ead2]/70">{c.description.replace(/<[^>]*>/g,'')}</p><span className="mt-5 inline-block text-sm font-bold text-[#d9ad42]">KHÁM PHÁ →</span></div></a>)}</div></main></div>
 if(pageSlug==='ve-chung-toi') return <div className="min-h-screen bg-[#060b14] text-[#f4ead2]"><TopNav slug={slug}/><main style={{fontFamily:"Arial, Helvetica, sans-serif"}}><section className="px-5 py-24 text-center" style={{background:'radial-gradient(circle at 50% 0%,#17334c 0,#070c16 55%)'}}><SectionTitle eyebrow="FAMILY & FRIENDS • PEACE • LOVE" title="THE TOP 1% LÀ AI?"/><p className="mx-auto max-w-4xl text-xl leading-9">Không phải những người giàu nhất hay có địa vị cao nhất. The Top 1% hướng tới những con người sống có <b className="text-[#e8c968]">CHÁNH KIẾN</b>, xây dựng <b className="text-[#e8c968]">SỰ NGHIỆP CHÂN MẠNG</b> và đi trên <b className="text-[#e8c968]">CUỘC ĐỜI CHÁNH ĐẠO</b>.</p></section><section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 md:grid-cols-2"><img src={imgs.who} alt="Cộng đồng The Top 1%" className="rounded-[40px] border border-[#d9ad42]/30"/><div><SectionTitle eyebrow="GIÁ TRỊ CỐT LÕI" title="SỐNG ĐỂ TẠO LẬP GIÁ TRỊ"/><p className="leading-8 text-[#f4ead2]/75">Thành công bằng cách giải quyết vấn đề xã hội, nâng đỡ người khác, kiến tạo giá trị và phụng sự cộng đồng.</p></div></section></main></div>
 return <div className="min-h-screen overflow-hidden bg-[#060b14] text-[#f4ead2]"><TopNav slug={slug}/>
 <main>
  <section className="relative grid min-h-[820px] place-items-center overflow-hidden px-5 py-24 text-center" style={{background:'radial-gradient(ellipse at 50% 20%,#17364c 0,#0a1422 34%,#050912 72%)'}}><div className="absolute inset-y-0 left-0 w-[18%] opacity-70" style={{background:'linear-gradient(90deg,#02050a,transparent),repeating-linear-gradient(75deg,transparent 0 38px,rgba(217,173,66,.09) 39px 40px)'}}/><div className="absolute inset-y-0 right-0 w-[18%] opacity-70" style={{background:'linear-gradient(270deg,#02050a,transparent),repeating-linear-gradient(105deg,transparent 0 38px,rgba(217,173,66,.09) 39px 40px)'}}/><div className="absolute left-[7%] top-0 h-full w-px bg-gradient-to-b from-transparent via-[#d9ad42]/50 to-transparent"/><div className="absolute right-[7%] top-0 h-full w-px bg-gradient-to-b from-transparent via-[#d9ad42]/50 to-transparent"/>
   <div className="absolute left-1/2 top-12 h-[620px] w-[min(88vw,760px)] -translate-x-1/2 rounded-t-[360px] border border-[#d9ad42]/25"/><div className="absolute left-1/2 top-20 h-[590px] w-[min(82vw,700px)] -translate-x-1/2 rounded-t-[330px] border border-[#d9ad42]/10"/>
   <div className="relative max-w-5xl"><div className="mx-auto mb-4 flex justify-center"><Lotus/></div><div className="mx-auto mb-6 text-xl font-bold tracking-[.2em] text-[#e8c968]" style={{fontFamily:serif}}>THE TOP 1%</div><p className="text-xs font-bold tracking-[.35em] text-[#d9ad42]">FAMILY & FRIENDS • PEACE • LOVE</p><h1 className="mt-8 text-5xl font-bold leading-[1.12] text-[#e8c968] md:text-7xl" style={{fontFamily:serif,textShadow:'0 0 28px rgba(217,173,66,.22)'}}>HỌC VIỆN<br/>THE TOP 1%</h1><Ornament/><h2 className="text-2xl font-semibold leading-[1.35] md:text-4xl" style={{fontFamily:serif}}>THỊNH VƯỢNG & HẠNH PHÚC<br/>TRÊN CON ĐƯỜNG MINH TRIẾT</h2><p className="mx-auto mt-6 max-w-3xl leading-8 text-[#f4ead2]/75">Kết nối tri thức • Rèn luyện thân tâm • Kiến tạo sự nghiệp • Lan tỏa giá trị<br/>Cùng bạn và gia đình vươn tới phiên bản tốt đẹp nhất.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><a href="#journey" className="rounded-full bg-[#d9ad42] px-7 py-3 font-bold text-[#07101a]">KHÁM PHÁ HÀNH TRÌNH</a><a href="#programs" className="rounded-full border border-[#d9ad42]/70 px-7 py-3 font-bold text-[#e8c968]">TRẢI NGHIỆM MIỄN PHÍ</a></div></div>
  </section>
  <section className="relative mx-auto max-w-7xl px-5 py-24"><div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#d9ad42]/35 to-transparent"/><SectionTitle eyebrow="THÂN • TÂM • TRÍ" title="3 TRỤ CỘT ĐÀO TẠO"/><div className="grid gap-7 md:grid-cols-3"><Arch title="TRƯỜNG SINH" tone="#07512f" icon="♨">6 bước Trường Sinh{String.fromCharCode(10)}Hơi thở diệu kỳ{String.fromCharCode(10)}Cân bằng đường huyết</Arch><Arch title="AN LẠC" tone="#52205f" icon="❀">Nâng tầm người{String.fromCharCode(10)}Chuyển hóa Tập Khí{String.fromCharCode(10)}Thực hành lòng biết ơn</Arch><Arch title="DOANH NHÂN TAM BẢO" tone="#124b7a" icon="◇">Doanh nhân Tam Bảo{String.fromCharCode(10)}Train The Coach{String.fromCharCode(10)}Kiến tạo Nhà Khai Vấn</Arch></div></section>
  <section className="border-y border-[#d9ad42]/15 bg-[#0b1320] px-5 py-20"><SectionTitle title="ĐIỀU QUAN TRỌNG KHÔNG PHẢI QUẢ — MÀ LÀ NHÂN"/><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-2"><div className="rounded-[32px] border border-[#d9ad42]/25 p-8 text-center"><div className="text-2xl font-bold text-[#e8c968]">♡ THÂN TRƯỜNG SINH<br/>♡ TÂM AN LẠC<br/>♡ TRÍ GIÁC NGỘ</div><p className="mt-5 leading-8 opacity-70">Tiền bạc • Danh vọng • Gia đình • Mối quan hệ • Sức khỏe</p></div><div className="rounded-[32px] border border-[#d9ad42]/25 p-8 text-center"><h3 className="text-2xl font-bold text-[#e8c968]">KHÔNG THỂ ĐỔI QUẢ THÌ ĐỔI NHÂN</h3><p className="mt-6  text-xl">“Muốn thay đổi số phận phải thay đổi TẬP KHÍ.”</p></div></div></section>
  <section id="about" className="border-y border-[#d9ad42]/20 bg-[#f3ead8] text-[#2b2418]"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 md:grid-cols-2"><div className="relative"><div className="absolute -inset-3 rounded-t-[180px] border border-[#d9ad42]/35"/><img src={imgs.founder} alt="Người sáng lập The Top 1%" className="relative w-full rounded-t-[170px] rounded-b-[30px] object-cover"/></div><div><p className="text-sm font-bold tracking-[.3em] text-[#d9ad42]">NGƯỜI SÁNG LẬP THE TOP 1%</p><h2 className="mt-5  text-3xl font-bold leading-tight text-[#e8c968] md:text-5xl">ỨNG DỤNG GIÁO LÝ ĐẠO PHẬT VÀO CUỘC SỐNG VÀ KINH DOANH</h2><Ornament/><p className="leading-8 text-[#f4ead2]/75">Hành trình chuyển hóa bắt đầu từ việc thấy rõ Tập Khí, quản trị cái Nhân và kiến tạo đời sống có chánh kiến, an lạc và giá trị.</p><a href={'/page/'+slug+'/ve-chung-toi'} className="mt-7 inline-block rounded-full border border-[#d9ad42]/60 px-6 py-3 text-[#e8c968]">TÌM HIỂU THE TOP 1%</a></div></div><div className="border-t border-[#c6a64a]/30 bg-[#0a1019] text-[#f4ead2]"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-6 px-5 py-7 text-center md:grid-cols-4">{[['10.000+','Học viên'],['100+','Chương trình'],['50+','Chuyên gia'],['95%','Hài lòng']].map(([n,l])=><div key={l}><div className="text-2xl font-bold text-[#e8c968]" style={{fontFamily:serif}}>{n}</div><div className="mt-1 text-sm opacity-70">{l}</div></div>)}</div></div></section>
  <section className="bg-[#0b1320] px-5 py-20"><SectionTitle title="THE TOP 1% — XÂY DỰNG 3 NỀN TẢNG CON NGƯỜI"/><div className="mx-auto grid max-w-7xl gap-7 md:grid-cols-3"><Arch title="GIA ĐÌNH & BẠN BÈ" tone="#0b5837">CLB Trường Sinh An Lạc{String.fromCharCode(10)}Môi trường nâng đỡ và phụng sự</Arch><Arch title="CHUYỂN ĐỔI TÂM THỨC" tone="#552267">Thấu hiểu Bản Ngã{String.fromCharCode(10)}Chuyển hóa Tập Khí{String.fromCharCode(10)}Khai mở Trí Tuệ</Arch><Arch title="SỰ NGHIỆP & THU NHẬP" tone="#154a78">Tự do tài chính{String.fromCharCode(10)}Sự nghiệp lợi mình, lợi người{String.fromCharCode(10)}Doanh Nhân Tam Bảo</Arch></div></section>
  <section className="relative overflow-hidden border-y border-[#d9ad42]/25 px-5 py-20 text-center" style={{background:'linear-gradient(rgba(8,13,22,.28),rgba(8,13,22,.78)),radial-gradient(circle at 50% 20%,#8c5b20,#0a1019 65%)'}}><div className="mx-auto max-w-4xl"><div className="text-xs font-bold tracking-[.35em] text-[#f4cf62]">ĐÁNH THỨC</div><h2 className="mt-4 text-4xl font-bold text-[#fff0c0] md:text-5xl" style={{fontFamily:serif}}>PHIÊN BẢN TỐT ĐẸP NHẤT CỦA BẠN</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-[#fff4d6]/85">Hành trình chuyển hóa Thân • Tâm • Trí để kiến tạo cuộc sống thịnh vượng, an lạc và phụng sự.</p><a href="#journey" className="mt-7 inline-block rounded-full bg-gradient-to-r from-[#c99227] via-[#ffe08a] to-[#c99227] px-8 py-3 font-bold text-[#201300] shadow-[0_0_30px_rgba(231,185,74,.45)]">THAM GIA NGAY →</a></div></section>
  <section id="journey" className="px-5 py-24 text-center" style={{background:'radial-gradient(circle,#163452 0,#07101c 60%)'}}><SectionTitle eyebrow="BẢN ĐỒ CHUYỂN HÓA" title="CON ĐƯỜNG VƯƠN TỚI THE TOP 1%"/><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-center gap-3">{['THÀNH VIÊN','LEADERS PHỤNG SỰ','LEADERS KHỞI XƯỚNG','DOANH NHÂN TAM BẢO','THE TOP 1%'].map((x,i)=><div key={x} className="flex items-center gap-3"><span className="rounded-full border border-[#d9ad42]/45 px-5 py-3 text-sm font-bold text-[#e8c968]">{x}</span>{i<4&&<span className="text-[#d9ad42]">→</span>}</div>)}</div></section>
  <section id="programs" className="mx-auto max-w-7xl px-5 py-24"><SectionTitle eyebrow="HỌC • HÀNH • CHUYỂN HÓA" title="CÁC KHÓA HỌC NỔI BẬT"/><div className="grid gap-6 md:grid-cols-3">{data.courses.slice(0,6).map(c=><a key={c.id} href={preview?'#':c.href} className="group overflow-hidden rounded-[28px] border border-[#d9ad42]/35 bg-[#0b1422] shadow-[0_20px_60px_rgba(0,0,0,.28)]"><div className="aspect-video overflow-hidden bg-[#101b2d]">{c.image&&<img src={c.image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>}</div><div className="p-6"><h3 className=" text-xl font-bold text-[#e8c968]">{c.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 opacity-65">{c.description.replace(/<[^>]*>/g,'')}</p></div></a>)}</div><div className="mt-10 text-center"><a href={'/page/'+slug+'/khoa-hoc'} className="rounded-full border border-[#d9ad42]/60 px-7 py-3 font-bold text-[#e8c968]">XEM TẤT CẢ CHƯƠNG TRÌNH</a></div></section>
  <section id="community" className="border-t border-[#d9ad42]/15 bg-[#08111d] px-5 py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 md:grid-cols-2"><div><SectionTitle eyebrow="CÙNG NHAU PHỤNG SỰ" title="HOẠT ĐỘNG CỘNG ĐỒNG"/><p className="text-center leading-9 text-[#f4ead2]/75">HƠI THỞ DIỆU KỲ • TREKKING & KHÁM PHÁ • QUỸ THIỆN HUỆ • DU LỊCH & DU XUÂN • KẾT NỐI DOANH NHÂN</p></div><img src={imgs.community} alt="Hoạt động cộng đồng" className="rounded-[40px] border border-[#d9ad42]/25"/></div></section>
 </main><footer className="border-t border-[#d9ad42]/20 bg-[#050912] px-5 py-12 text-center"><div className="mb-3 flex justify-center"><Lotus small/></div><div className="text-3xl font-bold text-[#e8c968]" style={{fontFamily:serif}}>THE TOP 1%</div><p className="mt-3 text-sm opacity-60">Thịnh vượng & Hạnh phúc trên con đường minh triết.</p></footer></div>
}