'use client'

import type { WebsiteData } from './WebsiteView'

const gold='#d9ad42'
const imgs={
 founder:'https://drive.google.com/uc?export=view&id=18xXBR6HfEX5mMrJ7xI6YKP0Az01ST5X5',
 who:'https://drive.google.com/uc?export=view&id=11jCgpbg3fKfayhKZxfZqYPiVOrik85KQ',
 foundations:'https://drive.google.com/uc?export=view&id=174m80UAa1q3d_vyG8QjTuvx9d_W8Yhp-',
 community:'https://drive.google.com/uc?export=view&id=1gExIBj-I7cgD_GJ5q1tUyMUWQsuWeZvJ'
}
function Ornament(){return <div className="flex items-center justify-center gap-3 my-5 opacity-80"><i className="h-px w-20 bg-gradient-to-r from-transparent to-[#d9ad42]"/><span className="text-[#d9ad42]">✦</span><i className="h-px w-20 bg-gradient-to-l from-transparent to-[#d9ad42]"/></div>}
function Arch({title,children,tone}:{title:string;children:React.ReactNode;tone:string}){return <div className="relative overflow-hidden rounded-t-[120px] rounded-b-[28px] border border-[#d9ad42]/50 p-8 pt-20 text-center min-h-[390px]" style={{background:`radial-gradient(circle at 50% 15%,${tone},#070d18 70%)`}}><div className="absolute inset-3 rounded-t-[108px] rounded-b-[22px] border border-[#d9ad42]/20"/><div className="relative"><div className="mx-auto mb-5 grid h-16 w-16 place-items-center rounded-full border border-[#d9ad42]/60 text-3xl text-[#e8c968]">✦</div><h3 className="font-serif text-2xl font-bold text-[#e8c968]">{title}</h3><Ornament/><div className="whitespace-pre-line leading-7 text-[#f4ead2]/85">{children}</div></div></div>}
function SectionTitle({eyebrow,title}:{eyebrow?:string;title:string}){return <div className="mx-auto mb-10 max-w-4xl text-center">{eyebrow&&<div className="mb-3 text-xs font-bold tracking-[.35em] text-[#d9ad42]">{eyebrow}</div>}<h2 className="font-serif text-3xl font-bold tracking-wide text-[#e8c968] md:text-5xl">{title}</h2><Ornament/></div>}
function TopNav({slug}:{slug:string}){return <header className="sticky top-0 z-30 border-b border-[#d9ad42]/20 bg-[#050a12]/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href={'/page/'+slug} className="font-serif text-xl font-bold text-[#e8c968]">THE TOP 1%</a><nav className="hidden gap-7 text-sm text-[#f4ead2]/80 md:flex"><a href={'/page/'+slug}>Trang chủ</a><a href="#about">Về The Top 1%</a><a href="#programs">Khóa học</a><a href="#community">Cộng đồng</a></nav><a href="#journey" className="rounded-full border border-[#d9ad42]/70 px-5 py-2 text-sm font-bold text-[#e8c968]">Khám phá</a></div></header>}
export default function TheTopSite({data,slug,pageSlug='',preview=false}:{data:WebsiteData;slug:string;pageSlug?:string;preview?:boolean}){
 if(pageSlug==='khoa-hoc'||pageSlug==='chuong-trinh') return <div className="min-h-screen bg-[#060b14] text-[#f4ead2]"><TopNav slug={slug}/><main className="mx-auto max-w-7xl px-5 py-16"><SectionTitle eyebrow="THE TOP 1% ACADEMY" title="CÁC KHÓA HỌC & CHƯƠNG TRÌNH"/><div className="grid gap-6 md:grid-cols-3">{data.courses.map(c=><a key={c.id} href={preview?'#':c.href} className="overflow-hidden rounded-3xl border border-[#d9ad42]/25 bg-[#0c1524]"><div className="aspect-[4/3] bg-[#101b2d]">{c.image&&<img src={c.image} alt="" className="h-full w-full object-cover"/>}</div><div className="p-6"><h3 className="font-serif text-xl font-bold text-[#e8c968]">{c.title}</h3><p className="mt-3 line-clamp-4 text-sm leading-6 text-[#f4ead2]/70">{c.description.replace(/<[^>]*>/g,'')}</p><span className="mt-5 inline-block text-sm font-bold text-[#d9ad42]">KHÁM PHÁ →</span></div></a>)}</div></main></div>
 if(pageSlug==='ve-chung-toi') return <div className="min-h-screen bg-[#060b14] text-[#f4ead2]"><TopNav slug={slug}/><main><section className="px-5 py-24 text-center" style={{background:'radial-gradient(circle at 50% 0%,#17334c 0,#070c16 55%)'}}><SectionTitle eyebrow="FAMILY & FRIENDS • PEACE • LOVE" title="THE TOP 1% LÀ AI?"/><p className="mx-auto max-w-4xl text-xl leading-9">Không phải những người giàu nhất hay có địa vị cao nhất. The Top 1% hướng tới những con người sống có <b className="text-[#e8c968]">CHÁNH KIẾN</b>, xây dựng <b className="text-[#e8c968]">SỰ NGHIỆP CHÂN MẠNG</b> và đi trên <b className="text-[#e8c968]">CUỘC ĐỜI CHÁNH ĐẠO</b>.</p></section><section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 md:grid-cols-2"><img src={imgs.who} alt="Cộng đồng The Top 1%" className="rounded-[40px] border border-[#d9ad42]/30"/><div><SectionTitle eyebrow="GIÁ TRỊ CỐT LÕI" title="SỐNG ĐỂ TẠO LẬP GIÁ TRỊ"/><p className="leading-8 text-[#f4ead2]/75">Thành công bằng cách giải quyết vấn đề xã hội, nâng đỡ người khác, kiến tạo giá trị và phụng sự cộng đồng.</p></div></section></main></div>
 return <div className="min-h-screen overflow-hidden bg-[#060b14] text-[#f4ead2]"><TopNav slug={slug}/>
 <main>
  <section className="relative grid min-h-[780px] place-items-center px-5 py-24 text-center" style={{background:'radial-gradient(ellipse at 50% 25%,#17364c 0,#0a1422 35%,#050912 72%)'}}>
   <div className="absolute left-1/2 top-12 h-[620px] w-[min(88vw,760px)] -translate-x-1/2 rounded-t-[360px] border border-[#d9ad42]/25"/><div className="absolute left-1/2 top-20 h-[590px] w-[min(82vw,700px)] -translate-x-1/2 rounded-t-[330px] border border-[#d9ad42]/10"/>
   <div className="relative max-w-5xl"><div className="mx-auto mb-6 grid h-24 w-24 place-items-center rounded-full border border-[#d9ad42]/60 text-5xl text-[#e8c968]">✦</div><p className="text-xs font-bold tracking-[.35em] text-[#d9ad42]">FAMILY & FRIENDS • PEACE • LOVE</p><h1 className="mt-8 font-serif text-5xl font-bold leading-tight text-[#e8c968] md:text-7xl">HỌC VIỆN<br/>THE TOP 1%</h1><Ornament/><h2 className="font-serif text-2xl font-semibold leading-relaxed md:text-4xl">THỊNH VƯỢNG & HẠNH PHÚC<br/>TRÊN CON ĐƯỜNG MINH TRIẾT</h2><p className="mx-auto mt-6 max-w-3xl leading-8 text-[#f4ead2]/75">Kết nối tri thức • Rèn luyện thân tâm • Kiến tạo sự nghiệp • Lan tỏa giá trị<br/>Cùng bạn và gia đình vươn tới phiên bản tốt đẹp nhất.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><a href="#journey" className="rounded-full bg-[#d9ad42] px-7 py-3 font-bold text-[#07101a]">KHÁM PHÁ HÀNH TRÌNH</a><a href="#programs" className="rounded-full border border-[#d9ad42]/70 px-7 py-3 font-bold text-[#e8c968]">TRẢI NGHIỆM MIỄN PHÍ</a></div></div>
  </section>
  <section className="mx-auto max-w-7xl px-5 py-20"><SectionTitle eyebrow="THÂN • TÂM • TRÍ" title="3 TRỤ CỘT ĐÀO TẠO"/><div className="grid gap-7 md:grid-cols-3"><Arch title="TRƯỜNG SINH" tone="#0b5837">6 bước Trường Sinh{String.fromCharCode(10)}Hơi thở diệu kỳ{String.fromCharCode(10)}Cân bằng đường huyết</Arch><Arch title="AN LẠC" tone="#552267">Nâng tầm người{String.fromCharCode(10)}Chuyển hóa Tập Khí{String.fromCharCode(10)}Thực hành lòng biết ơn</Arch><Arch title="DOANH NHÂN TAM BẢO" tone="#154a78">Doanh nhân Tam Bảo{String.fromCharCode(10)}Train The Coach{String.fromCharCode(10)}Kiến tạo Nhà Khai Vấn</Arch></div></section>
  <section className="border-y border-[#d9ad42]/15 bg-[#0b1320] px-5 py-20"><SectionTitle title="ĐIỀU QUAN TRỌNG KHÔNG PHẢI QUẢ — MÀ LÀ NHÂN"/><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-2"><div className="rounded-[32px] border border-[#d9ad42]/25 p-8 text-center"><div className="text-2xl font-bold text-[#e8c968]">♡ THÂN TRƯỜNG SINH<br/>♡ TÂM AN LẠC<br/>♡ TRÍ GIÁC NGỘ</div><p className="mt-5 leading-8 opacity-70">Tiền bạc • Danh vọng • Gia đình • Mối quan hệ • Sức khỏe</p></div><div className="rounded-[32px] border border-[#d9ad42]/25 p-8 text-center"><h3 className="text-2xl font-bold text-[#e8c968]">KHÔNG THỂ ĐỔI QUẢ THÌ ĐỔI NHÂN</h3><p className="mt-6 font-serif text-xl">“Muốn thay đổi số phận phải thay đổi TẬP KHÍ.”</p></div></div></section>
  <section id="about" className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-24 md:grid-cols-2"><div className="relative"><div className="absolute -inset-3 rounded-t-[180px] border border-[#d9ad42]/35"/><img src={imgs.founder} alt="Người sáng lập The Top 1%" className="relative w-full rounded-t-[170px] rounded-b-[30px] object-cover"/></div><div><p className="text-sm font-bold tracking-[.3em] text-[#d9ad42]">NGƯỜI SÁNG LẬP THE TOP 1%</p><h2 className="mt-5 font-serif text-3xl font-bold leading-tight text-[#e8c968] md:text-5xl">ỨNG DỤNG GIÁO LÝ ĐẠO PHẬT VÀO CUỘC SỐNG VÀ KINH DOANH</h2><Ornament/><p className="leading-8 text-[#f4ead2]/75">Hành trình chuyển hóa bắt đầu từ việc thấy rõ Tập Khí, quản trị cái Nhân và kiến tạo đời sống có chánh kiến, an lạc và giá trị.</p><a href={'/page/'+slug+'/ve-chung-toi'} className="mt-7 inline-block rounded-full border border-[#d9ad42]/60 px-6 py-3 text-[#e8c968]">TÌM HIỂU THE TOP 1%</a></div></section>
  <section className="bg-[#0b1320] px-5 py-20"><SectionTitle title="THE TOP 1% — XÂY DỰNG 3 NỀN TẢNG CON NGƯỜI"/><div className="mx-auto grid max-w-7xl gap-7 md:grid-cols-3"><Arch title="GIA ĐÌNH & BẠN BÈ" tone="#0b5837">CLB Trường Sinh An Lạc{String.fromCharCode(10)}Môi trường nâng đỡ và phụng sự</Arch><Arch title="CHUYỂN ĐỔI TÂM THỨC" tone="#552267">Thấu hiểu Bản Ngã{String.fromCharCode(10)}Chuyển hóa Tập Khí{String.fromCharCode(10)}Khai mở Trí Tuệ</Arch><Arch title="SỰ NGHIỆP & THU NHẬP" tone="#154a78">Tự do tài chính{String.fromCharCode(10)}Sự nghiệp lợi mình, lợi người{String.fromCharCode(10)}Doanh Nhân Tam Bảo</Arch></div></section>
  <section id="journey" className="px-5 py-24 text-center" style={{background:'radial-gradient(circle,#163452 0,#07101c 60%)'}}><SectionTitle eyebrow="BẢN ĐỒ CHUYỂN HÓA" title="CON ĐƯỜNG VƯƠN TỚI THE TOP 1%"/><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-center gap-3">{['THÀNH VIÊN','LEADERS PHỤNG SỰ','LEADERS KHỞI XƯỚNG','DOANH NHÂN TAM BẢO','THE TOP 1%'].map((x,i)=><div key={x} className="flex items-center gap-3"><span className="rounded-full border border-[#d9ad42]/45 px-5 py-3 text-sm font-bold text-[#e8c968]">{x}</span>{i<4&&<span className="text-[#d9ad42]">→</span>}</div>)}</div></section>
  <section id="programs" className="mx-auto max-w-7xl px-5 py-24"><SectionTitle eyebrow="HỌC • HÀNH • CHUYỂN HÓA" title="CÁC KHÓA HỌC NỔI BẬT"/><div className="grid gap-6 md:grid-cols-3">{data.courses.slice(0,6).map(c=><a key={c.id} href={preview?'#':c.href} className="group overflow-hidden rounded-[28px] border border-[#d9ad42]/20 bg-[#0b1422]"><div className="aspect-video overflow-hidden bg-[#101b2d]">{c.image&&<img src={c.image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>}</div><div className="p-6"><h3 className="font-serif text-xl font-bold text-[#e8c968]">{c.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 opacity-65">{c.description.replace(/<[^>]*>/g,'')}</p></div></a>)}</div><div className="mt-10 text-center"><a href={'/page/'+slug+'/khoa-hoc'} className="rounded-full border border-[#d9ad42]/60 px-7 py-3 font-bold text-[#e8c968]">XEM TẤT CẢ CHƯƠNG TRÌNH</a></div></section>
  <section id="community" className="border-t border-[#d9ad42]/15 bg-[#08111d] px-5 py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 md:grid-cols-2"><div><SectionTitle eyebrow="CÙNG NHAU PHỤNG SỰ" title="HOẠT ĐỘNG CỘNG ĐỒNG"/><p className="text-center leading-9 text-[#f4ead2]/75">HƠI THỞ DIỆU KỲ • TREKKING & KHÁM PHÁ • QUỸ THIỆN HUỆ • DU LỊCH & DU XUÂN • KẾT NỐI DOANH NHÂN</p></div><img src={imgs.community} alt="Hoạt động cộng đồng" className="rounded-[40px] border border-[#d9ad42]/25"/></div></section>
 </main><footer className="border-t border-[#d9ad42]/20 px-5 py-12 text-center"><div className="font-serif text-3xl font-bold text-[#e8c968]">THE TOP 1%</div><p className="mt-3 text-sm opacity-60">Thịnh vượng & Hạnh phúc trên con đường minh triết.</p></footer></div>
}