'use client'

import { ChangeEvent, useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { cloneNode, documentError, Kind, kinds, labels, makeNode, moveNode, NodeStyle, parseDocument, removeNode, uid, updateNode, walkNodes, WebsiteDocument, WebsiteNode } from '@/lib/website/document'
import WebsiteImport from './WebsiteImport'
import WebsiteView, { WebsiteData } from './WebsiteView'
import { makeSection, sections } from '@/lib/website/sections'

type History = { date: string; document: WebsiteDocument }[]
type Loaded = { profile: { slug: string; isActive: boolean; canUseCrm: boolean }; document: WebsiteDocument; revision: number; history: History; published: boolean; data: WebsiteData; templates: { key: string; name: string; document: WebsiteDocument; notes: string[] }[] }
const inputClass = 'w-full border border-gray-300 rounded-lg p-2 bg-white text-gray-900'
const buttonClass = 'border border-gray-300 rounded-lg px-3 py-2 bg-white hover:bg-violet-50 disabled:opacity-40 text-sm'

export default function WebsiteEditor() {
  const [loaded,setLoaded] = useState<Loaded | null>(null)
  const [doc,setDoc] = useState<WebsiteDocument | null>(null)
  const [pageId,setPageId] = useState(''); const [selected,setSelected] = useState('')
  const [mobile,setMobile] = useState(false); const [preview,setPreview] = useState(false)
  const [busy,setBusy] = useState(false); const [dirty,setDirty] = useState(false); const [message,setMessage] = useState('')
  const [undo,setUndo] = useState<WebsiteDocument[]>([]); const [redo,setRedo] = useState<WebsiteDocument[]>([])
  const [drag,setDrag] = useState(''); const importInput = useRef<HTMLInputElement>(null)
  useEffect(() => { let cancelled = false; fetch('/api/websites',{ cache: 'no-store' }).then(async response => { const value = await response.json(); if(!response.ok) throw new Error(value.error || 'Không thể mở website.'); if(!cancelled) { const document = parseDocument(value.document); setLoaded(value); setDoc(document); setPageId(document.pages[0].id) } }).catch(e => { if(!cancelled) setMessage(e.message) }); return () => { cancelled = true } },[])
  useEffect(() => { if(!dirty) return; const before = (e: BeforeUnloadEvent) => { e.preventDefault(); e.returnValue = '' }; window.addEventListener('beforeunload',before); return () => window.removeEventListener('beforeunload',before) },[dirty])
  function change(next: WebsiteDocument) { if(!doc || busy) return; setUndo(list => [...list.slice(-29),doc]); setRedo([]); setDoc(next); setDirty(true) }
  function exportJson() { if(!doc) return; const url = URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{ type: 'application/json' })); const a = document.createElement('a'); a.href=url; a.download='website.json'; a.click(); URL.revokeObjectURL(url) }
  async function importJson(e: ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]; e.target.value = ''; if(!file) return
    try { if(file.size > 600000) throw new Error('Tệp tối đa 600 KB.'); const next = parseDocument(JSON.parse((await file.text()).replace(/^\uFEFF/,''))); change(next); setPageId(next.pages[0].id); setSelected(''); setMessage('Đã nhập vào bản nháp. Bạn có thể hoàn tác trước khi lưu.') }
    catch(e) { setMessage(documentError(e)) }
  }
  async function persist(action: 'save' | 'publish' | 'unpublish' | 'restore', historyIndex?: number) {
    if(!loaded || !doc || busy) return
    if(action === 'restore' && dirty && !window.confirm('Khôi phục sẽ thay bản nháp chưa lưu. Bạn đã xuất JSON hoặc muốn tiếp tục?')) return
    if(action === 'unpublish' && !window.confirm('Ẩn thiết kế mới và hiển thị trang cũ tại đường dẫn hiện tại?')) return
    setBusy(true); setMessage('')
    try {
      if(action === 'save' || action === 'publish') parseDocument(doc)
      const response = await fetch('/api/websites',{ method:'POST',headers:{'Content-Type':'application/json'},body: JSON.stringify({ action, revision: loaded.revision, ...(action === 'save' || action === 'publish' ? { document: doc } : {}), ...(historyIndex != null ? { historyIndex } : {}) }) })
      const value = await response.json(); if(!response.ok) throw new Error(value.error || 'Không thể lưu.')
      setLoaded({ ...loaded,...value }); setDoc(parseDocument(value.document)); setDirty(false)
      if(action === 'restore') { setPageId(value.document.pages[0].id); setSelected(''); setUndo([]); setRedo([]) }
      setMessage(action === 'publish' ? 'Đã xuất bản thiết kế tự do. Website hiển thị theo mẫu đang chọn trong Quản lý website.' : action === 'unpublish' ? 'Đã ẩn thiết kế mới. Trang cũ tiếp tục hoạt động.' : action === 'restore' ? 'Đã khôi phục vào bản nháp. Cần xuất bản để cập nhật website.' : 'Đã lưu bản nháp.')
    } catch(e) { setMessage(documentError(e)) } finally { setBusy(false) }
  }
  if(!doc || !loaded) return <div className="p-8 max-w-2xl mx-auto"><h1 className="text-2xl font-bold mb-4">Thiết kế website riêng</h1><p role="status">{message || 'Đang tải…'}</p><Link href="/tools/my-site/manage" className="text-violet-600 underline">Về quản lý website</Link></div>
  const page = doc.pages.find(p => p.id === pageId) || doc.pages[0]
  const node = walkNodes(page.nodes).find(n => n.id === selected)
  function nodesChange(nodes: WebsiteNode[]) { change({ ...doc!, pages: doc!.pages.map(p => p.id === page.id ? { ...p,nodes } : p) }) }
  function patchNode(patch: Partial<WebsiteNode>) { if(node) nodesChange(updateNode(page.nodes,node.id,n => ({ ...n,...patch }))) }
  function add(kind: Kind) { const n = makeNode(kind); nodesChange(node?.kind === 'container' ? updateNode(page.nodes,node.id,parent => ({ ...parent,children: [...parent.children,n] })) : [...page.nodes,n]); setSelected(n.id) }
  function addSection(key: string) { const n = makeSection(key); nodesChange([...page.nodes,n]); setSelected(n.id) }
  function applyTemplate(key: string) {
    const source = loaded!.templates.find(template => template.key === key)
    if(!source) return
    if(dirty && !window.confirm('Áp dụng mẫu sẽ thay bản nháp chưa lưu. Bạn có muốn tiếp tục?')) return
    const next = structuredClone(source.document)
    change(next); setPageId(next.pages[0].id); setSelected(''); setMessage(source.notes.join('\n'))
  }
  function reorder(id: string, parent: string | null, nodes: WebsiteNode[], direction: number) { const index = nodes.findIndex(n => n.id === id); if(index + direction < 0 || index + direction >= nodes.length) return; const before = direction < 0 ? nodes[index-1].id : nodes[index+2]?.id; nodesChange(moveNode(page.nodes,id,parent,before)) }
  function tree(nodes: WebsiteNode[], parent: string | null = null) {
    return <ul className="grid gap-2">{nodes.map(n => <li key={n.id} className="pl-2 border-l border-gray-300">
      <div className={'flex gap-1 rounded-lg p-1 ' + (selected === n.id ? 'bg-violet-100' : 'bg-gray-50')} draggable={!busy} onDragStart={e => { e.stopPropagation(); setDrag(n.id); e.dataTransfer.setData('text/plain',n.id) }} onDragOver={e => { e.preventDefault(); e.stopPropagation() }} onDrop={e => { e.preventDefault(); e.stopPropagation(); nodesChange(moveNode(page.nodes,drag || e.dataTransfer.getData('text/plain'),parent,n.id)); setDrag('') }}>
        <button type="button" className="text-left text-xs flex-1 p-1 truncate" onClick={() => setSelected(n.id)} title="Kéo để đặt trước thành phần này">⠿ {labels[n.kind]} · {n.text.slice(0,20)}</button>
        <button type="button" title="Lên" onClick={() => reorder(n.id,parent,nodes,-1)}>↑</button><button type="button" title="Xuống" onClick={() => reorder(n.id,parent,nodes,1)}>↓</button>
      </div>
      {n.kind === 'container' && <div className="ml-2 pt-2" onDragOver={e => { e.preventDefault(); e.stopPropagation() }} onDrop={e => { e.preventDefault(); e.stopPropagation(); nodesChange(moveNode(page.nodes,drag || e.dataTransfer.getData('text/plain'),n.id)); setDrag('') }}>{tree(n.children,n.id)}<button type="button" className="text-xs text-violet-700 p-2 border border-dashed w-full mt-1" onClick={() => setSelected(n.id)}>Thả vào bố cục / chọn để thêm</button></div>}
    </li>)}</ul>
  }
  const style = node ? (mobile ? node.mobile : node.style) : {}
  function setStyle(key: keyof NodeStyle, value: string) { if(!node) return; const next = { ...style }; if(value === '') delete next[key]; else Object.assign(next,{ [key]: ['background','color','align','fontFamily'].includes(key) ? value : Number(value) }); patchNode(mobile ? { mobile: next } : { style: next }) }
  const numberFields: [keyof NodeStyle,string,number,number][] = [['padding','Khoảng trong',0,240],['gap','Khoảng cách',0,120],['columns','Số cột',1,6],['fontSize','Cỡ chữ',10,120],['width','Rộng (%)',5,100],['radius','Bo góc',0,100],['maxWidth','Rộng tối đa',200,2400],['minHeight','Cao tối thiểu / HTML',0,2000]]
  return <div className="bg-gray-100 text-gray-900 min-h-screen">
    <header className="sticky top-0 z-30 bg-white border-b p-3 flex flex-wrap items-center gap-2"><Link href="/tools/my-site/manage" className="text-sm mr-3">← Quản lý website</Link><h1 className="font-bold mr-auto">Thiết kế website <span className="text-xs font-normal">{dirty ? '• Chưa lưu' : '• Đã lưu'}{loaded.published ? ' · Có bản công khai' : ' · Chưa xuất bản'}</span></h1><button className={buttonClass} disabled={!undo.length || busy} onClick={() => { const next = undo.at(-1)!; setUndo(undo.slice(0,-1)); setRedo([...redo,doc]); setDoc(next); setDirty(true) }}>Hoàn tác</button><button className={buttonClass} disabled={!redo.length || busy} onClick={() => { const next = redo.at(-1)!; setRedo(redo.slice(0,-1)); setUndo([...undo,doc]); setDoc(next); setDirty(true) }}>Làm lại</button><button className={buttonClass} onClick={() => setMobile(!mobile)}>{mobile ? 'Điện thoại' : 'Máy tính'}</button><button className={buttonClass} onClick={() => setPreview(!preview)}>{preview ? 'Sửa thiết kế' : 'Xem trước'}</button><button className={buttonClass} disabled={busy} onClick={() => persist('save')}>Lưu nháp</button><button className="bg-violet-700 text-white rounded-lg px-4 py-2 disabled:opacity-40" disabled={busy || !loaded.profile.isActive} onClick={() => persist('publish')}>{busy ? 'Đang xử lý…' : 'Xuất bản'}</button><a className={buttonClass} target="_blank" rel="noreferrer" href={'/page/' + loaded.profile.slug}>Mở website ↗</a></header>
    <div role="status" aria-live="polite" className="px-4 py-2 text-sm bg-violet-50 whitespace-pre-line">{message || 'Chọn trang → thêm bố cục / thành phần → sửa bên phải → lưu nháp hoặc xuất bản.'}{!loaded.profile.isActive && <p>Trang cần quản trị viên kích hoạt trước khi xuất bản.</p>}</div>
    <fieldset disabled={busy} className="grid grid-cols-1 xl:grid-cols-[280px_minmax(0,1fr)_300px] gap-4 p-4 min-w-0">
      {!preview && <aside className="bg-white rounded-xl p-4 space-y-5 xl:max-h-[calc(100vh-150px)] overflow-auto">
        <section><h2 className="font-bold mb-2">Trang trong website</h2><select className={inputClass} value={page.id} onChange={e => { setPageId(e.target.value); setSelected('') }}>{doc.pages.map(p => <option key={p.id} value={p.id}>{p.title}{!p.slug ? ' (Trang chủ)' : ''}</option>)}</select><div className="flex gap-2 mt-2"><button className={buttonClass} disabled={doc.pages.length >= 30} onClick={() => { const p = { id: uid(),title: 'Trang mới',slug: 'trang-' + Date.now(),nodes: [] }; change({ ...doc,pages: [...doc.pages,p] }); setPageId(p.id); setSelected('') }}>+ Trang</button><button className={buttonClass} disabled={!page.slug} onClick={() => { if(window.confirm('Xóa trang này khỏi bản nháp?')) { change({ ...doc,pages: doc.pages.filter(p => p.id !== page.id) }); setPageId(doc.pages[0].id); setSelected('') } }}>Xóa trang</button></div><label className="text-xs block mt-2">Tên trang<input className={inputClass} value={page.title} onChange={e => change({ ...doc,pages: doc.pages.map(p => p.id === page.id ? { ...p,title:e.target.value } : p) })} /></label>{page.slug !== '' && <label className="text-xs block mt-2">Đường dẫn (chữ thường, số, dấu -)<input className={inputClass} value={page.slug} onChange={e => change({ ...doc,pages: doc.pages.map(p => p.id === page.id ? { ...p,slug:e.target.value || page.slug } : p) })} /></label>}</section>
        <section><h2 className="font-bold mb-2">Mẫu sales page khóa học</h2><select className={inputClass} aria-label="Mẫu sales page khóa học" value="" onChange={e => { if(e.target.value) applyTemplate(e.target.value) }}><option value="">Chọn mẫu để áp dụng…</option>{loaded.templates.map(t => <option key={t.key} value={t.key}>{t.name}</option>)}</select><p className="text-xs text-gray-500 mt-1">Dùng các mẫu có sẵn trong phần khóa học. Nội dung được chuyển thành khối chỉnh sửa; bố cục có thể khác trang khóa học gốc. Áp dụng thay toàn bộ bản nháp và có thể hoàn tác.</p></section>
        <WebsiteImport onApply={n => {
          if (page.nodes.length && !window.confirm('Thay nội dung trang đang chọn bằng HTML/ZIP? Các trang khác được giữ nguyên. Bạn có thể hoàn tác.')) return
          nodesChange([n]); setSelected(n.id); setMessage('Đã nhập nguyên trang vào bản nháp. Chọn khóa học cho nút đăng ký hoặc thêm khối Form tư vấn. Có thể hoàn tác.')
        }} />
        <section><h2 className="font-bold mb-2">Thêm thành phần</h2><p className="text-xs text-gray-500 mb-2">{node?.kind === 'container' ? 'Thêm vào bố cục đang chọn.' : 'Thêm cuối trang. Chọn bố cục để thêm bên trong.'}</p><div className="grid grid-cols-2 gap-2">{kinds.filter(kind => kind !== 'course-hero' && kind !== 'imported-page').map(kind => <button className={buttonClass + ' text-left'} key={kind} onClick={() => add(kind)}>{labels[kind]}</button>)}</div></section>
        <section><h2 className="font-bold mb-2">Cấu trúc kéo thả</h2>{tree(page.nodes)}<button className="p-3 text-xs border border-dashed w-full mt-2" onClick={() => setSelected('')} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); nodesChange(moveNode(page.nodes,drag || e.dataTransfer.getData('text/plain'),null)); setDrag('') }}>Thả cuối trang / chọn gốc trang</button></section>
        <section><h2 className="font-bold mb-2">Section dựng sẵn</h2><select className={inputClass} value="" onChange={e => { if(e.target.value) addSection(e.target.value) }}><option value="">+ Thêm section vào trang…</option>{sections.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><p className="text-xs text-gray-500 mt-1">Mỗi section là bố cục và các thành phần độc lập; có thể sửa, thêm bớt và kéo sang bố cục khác.</p></section>
        <section className="grid gap-2"><button className={buttonClass} onClick={exportJson}>Xuất JSON</button><button className={buttonClass} onClick={() => importInput.current?.click()}>Nhập JSON</button><input ref={importInput} type="file" accept=".json,application/json" className="hidden" onChange={importJson} /><p className="text-xs text-gray-500">JSON theo cấu trúc website v1. Xuất bản nháp để lấy mẫu cấu trúc; mã HTML/CSS dùng khối riêng.</p></section>
        {!!loaded.history.length && <section><h2 className="font-bold mb-2">Lịch sử xuất bản</h2>{loaded.history.map((h,i) => <button key={i} className={buttonClass + ' w-full mb-2'} onClick={() => persist('restore',i)}>Khôi phục nháp · {new Date(h.date).toLocaleString('vi-VN')}</button>)}</section>}
        {loaded.published && <button className={buttonClass} disabled={dirty} title={dirty ? 'Lưu bản nháp trước khi ẩn thiết kế' : ''} onClick={() => persist('unpublish')}>Ẩn thiết kế, dùng trang cũ</button>}
      </aside>}
      <section className={'min-w-0 overflow-auto ' + (preview ? 'xl:col-span-3' : '')}><div className="mx-auto bg-white shadow-lg rounded-xl overflow-hidden" style={{ width: mobile ? 390 : '100%',maxWidth: '100%' }}><WebsiteView document={doc} data={loaded.data} slug={loaded.profile.slug} pageSlug={page.slug} preview mobile={mobile} selected={preview ? undefined : selected} onSelect={preview ? undefined : setSelected} /></div></section>
      {!preview && <aside className="bg-white rounded-xl p-4 space-y-4 xl:max-h-[calc(100vh-150px)] overflow-auto">
        <h2 className="font-bold">{node ? labels[node.kind] : 'Thương hiệu website'}</h2>
        {!node && <section className="grid gap-3 border-b pb-4">
          <label className="text-sm">Chiều rộng website<input className={inputClass} type="number" min={320} max={2400} value={doc.layout.maxWidth} onChange={e => change({ ...doc,layout:{ ...doc.layout,maxWidth:Number(e.target.value) } })} /></label>
          <label className="text-sm">Khoảng trong trang<input className={inputClass} type="number" min={0} max={100} value={doc.layout.padding} onChange={e => change({ ...doc,layout:{ ...doc.layout,padding:Number(e.target.value) } })} /></label>
          <label className="text-sm">Khoảng giữa thành phần<input className={inputClass} type="number" min={0} max={120} value={doc.layout.gap} onChange={e => change({ ...doc,layout:{ ...doc.layout,gap:Number(e.target.value) } })} /></label>
          <label className="text-sm">Kiểu chữ<select className={inputClass} value={doc.layout.fontFamily} onChange={e => change({ ...doc,layout:{ ...doc.layout,fontFamily:e.target.value as NodeStyle['fontFamily'] & string } })}><option value="inherit">Font của hệ thống</option><option value="sans-serif">Không chân</option><option value="serif">Có chân</option><option value="monospace">Monospace</option></select></label>
          <label className="text-sm"><input type="checkbox" checked={doc.layout.showHeader} onChange={e => change({ ...doc,layout:{ ...doc.layout,showHeader:e.target.checked } })} /> Dùng menu tự động</label>
          <label className="text-sm"><input type="checkbox" checked={doc.layout.showFooter} onChange={e => change({ ...doc,layout:{ ...doc.layout,showFooter:e.target.checked } })} /> Dùng chân trang tự động</label>
          <p className="text-xs text-gray-500">Có thể tắt menu và chân trang để tự thiết kế bằng bố cục hoặc HTML/CSS.</p>
        </section>}
        {!node ? <><label className="block text-sm">Tên thương hiệu<input className={inputClass} value={doc.name} onChange={e => change({ ...doc,name:e.target.value })} /></label><label className="block text-sm">Mô tả SEO<textarea className={inputClass} value={doc.description} onChange={e => change({ ...doc,description:e.target.value })} maxLength={500} /></label><label className="block text-sm">Màu chủ đạo<input className={inputClass} type="color" value={doc.color} onChange={e => change({ ...doc,color:e.target.value })} /></label><label className="block text-sm">Nền website<input className={inputClass} type="color" value={doc.background} onChange={e => change({ ...doc,background:e.target.value })} /></label><p className="text-sm text-gray-500">Chọn thành phần trên trang hoặc trong cây cấu trúc để sửa.</p></> : <>
          <label className="block text-sm">Nội dung / tiêu đề / mô tả ảnh<textarea className={inputClass} value={node.text} onChange={e => patchNode({ text:e.target.value })} rows={4} /></label>
          {['image','video','button','affiliate'].includes(node.kind) && <label className="block text-sm">URL<input className={inputClass} value={node.url} onChange={e => patchNode({ url:e.target.value })} placeholder={node.kind === 'affiliate' ? '/khoa-hoc/MA-KHOA?ref=MA-CUA-BAN' : 'https://… hoặc /…'} /></label>}
          {node.kind === 'affiliate' && <p className="text-xs text-gray-500">Dán liên kết affiliate được hệ thống cấp. Bản xuất bản giữ tham số ref; quy tắc ghi nhận vẫn do hệ thống affiliate xử lý.</p>}
          {node.kind === 'course-hero' && <div><label className="block text-sm font-medium">Khóa học chính<select className={inputClass} value={node.courseIds.length === 1 ? node.courseIds[0] : ''} onChange={e => patchNode({ courseIds:e.target.value ? [Number(e.target.value)] : [] })}><option value="">Chọn một khóa học…</option>{loaded.data.courses.map(course => <option key={course.id} value={course.id}>{course.title}</option>)}</select></label><p className="mt-2 text-xs text-gray-500">Tên, ảnh, mô tả và liên kết đăng ký lấy từ khóa học đã chọn. Các phần chương trình, lợi ích và giới thiệu giáo viên là nội dung mẫu cần chỉnh lại.</p>{!loaded.data.courses.length && <p className="mt-2 text-xs text-amber-700">Chưa có khóa học trong nguồn của website. Kiểm tra Dữ liệu & giáo viên tại Quản lý website.</p>}</div>}
          {node.kind === 'testimonials' && walkNodes(page.nodes).some(item => item.kind === 'course-hero') && <p className="text-xs text-gray-500">Để trống để lấy đánh giá của khóa học chính. Nếu chưa có đánh giá, website công khai sẽ ẩn khối này.</p>}
          {['courses','testimonials'].includes(node.kind) && <div><p className="text-sm font-medium">{walkNodes(page.nodes).some(item => item.kind === 'course-hero') ? node.kind === 'testimonials' ? 'Chọn khóa học (để trống = khóa học chính)' : 'Chọn khóa học (để trống = các khóa khác của trang)' : 'Chọn khóa học (để trống = tất cả của trang)'}</p>{loaded.data.courses.map(c => <label key={c.id} className="flex gap-2 text-xs mt-2"><input type="checkbox" checked={node.courseIds.includes(c.id)} onChange={e => patchNode({ courseIds:e.target.checked ? [...node.courseIds,c.id] : node.courseIds.filter(id => id !== c.id) })} />{c.title}</label>)}</div>}
          {node.kind === 'imported-page' && <><p className="text-xs text-gray-500">Trang nhập giữ nguyên bố cục. Muốn sửa HTML, chỉnh file bên ngoài rồi nhập lại. Nút đăng ký nối tới khóa học đã chọn; nếu để trống, nối tới khối Form tư vấn trong trang.</p><label className="block text-sm">Khóa học cho nút đăng ký<select className={inputClass} value={node.courseIds[0] || ''} onChange={e => patchNode({ courseIds: e.target.value ? [Number(e.target.value)] : [] })}><option value="">Dùng khối Form tư vấn</option>{loaded.data.courses.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label></>}
          {node.kind === 'html' && <><p className="text-xs text-gray-500">HTML/CSS trong khung cách ly. JavaScript và form tự viết không chạy. Dùng thành phần Form CRM / khóa học để nối dữ liệu thật.</p><label className="block text-sm">HTML<textarea className={inputClass + ' font-mono text-xs'} rows={10} value={node.html} onChange={e => patchNode({ html:e.target.value })} /></label><label className="block text-sm">CSS<textarea className={inputClass + ' font-mono text-xs'} rows={6} value={node.css} onChange={e => patchNode({ css:e.target.value })} /></label></>}
          <h3 className="font-bold pt-3 border-t">Giao diện {mobile ? 'điện thoại' : 'máy tính'}</h3><p className="text-xs text-gray-500">Ô trống kế thừa mặc định. Trên điện thoại, bố cục mặc định 1 cột.</p><div className="grid grid-cols-2 gap-3">{numberFields.filter(([key]) => key !== 'columns' || node.kind === 'container').map(([key,label,min,max]) => <label key={key} className="text-xs">{label}<input className={inputClass} type="number" min={min} max={max} step={1} value={style[key] ?? ''} onChange={e => setStyle(key,e.target.value)} /></label>)}</div>
          {(['background','color'] as const).map(key => <label key={key} className="block text-sm">{key === 'background' ? 'Màu nền' : 'Màu chữ'}<input className={inputClass} value={style[key] || ''} placeholder="#ffffff / transparent" onChange={e => setStyle(key,e.target.value)} /></label>)}<label className="block text-sm">Căn chữ<select className={inputClass} value={style.align || ''} onChange={e => setStyle('align',e.target.value)}><option value="">Mặc định</option><option value="left">Trái</option><option value="center">Giữa</option><option value="right">Phải</option></select></label>
          <div className="flex gap-2"><button className={buttonClass} onClick={() => { const copy = cloneNode(node); const all = [...page.nodes,copy]; nodesChange(all); setSelected(copy.id) }}>Nhân bản</button><button className={buttonClass} onClick={() => { nodesChange(removeNode(page.nodes,node.id)); setSelected('') }}>Xóa</button></div>
        </>}
      </aside>}
    </fieldset>
  </div>
}
