'use client'
/* eslint-disable @next/next/no-html-link-for-pages -- Các công cụ quản lý có vòng đời riêng. */
import {useEffect,useState} from 'react'
import {moduleKeys,moduleLabels,moduleScopes,noModules,type WebsiteAccess} from '@/lib/website/access'
import type {DomainModules} from '@/lib/website/domain-shared'
type Snapshot={access:WebsiteAccess;basic:DomainModules;admin:boolean;name:string;slug:string;configured:boolean;domains:{hostname:string;enabled:boolean}[]}
export default function WebsiteManager() {
  const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const [basic,setBasic]=useState<DomainModules>(noModules),[extra,setExtra]=useState<DomainModules>(noModules),[enabled,setEnabled]=useState<DomainModules>(noModules)
  function receive(value:Snapshot){setData(value);setBasic(value.basic);setExtra(value.access.extra);setEnabled(value.access.enabled)}
  useEffect(()=>{const abort=new AbortController();fetch('/api/websites/access',{signal:abort.signal}).then(async r=>{const value=await r.json();if(!r.ok)throw new Error(value.error);receive(value)}).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort()},[])
  async function save(body:object){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/websites/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw new Error(value.error);receive(value);setMessage('Đã lưu cấu hình. Mở lại website để xem thay đổi.')}catch(e){setError(e instanceof Error ? e.message : 'Không thể lưu.')}finally{setBusy(false)}}
  const view=data?.domains.find(d=>d.enabled)
  return <main className="min-h-screen bg-slate-50 text-slate-900 p-4 sm:p-8"><div className="max-w-5xl mx-auto grid gap-6">
    <a href="/tools/pages?tab=my-site" className="text-sm text-violet-700">← Trang của tôi</a>
    <header><p className="text-sm text-violet-700 mb-2">Không gian quản lý</p><h1 className="text-3xl font-bold">Website của tôi</h1><p className="text-slate-600 mt-2">{data?.name || 'Quản lý nội dung, tên miền và chức năng ở một nơi.'}</p></header>
    <nav aria-label="Quản lý website" className="grid gap-3 sm:grid-cols-3">{[['/tools/my-site/design','Trang & giao diện','Thiết kế trang, thêm nội dung và sắp xếp các trang trong menu.'],['/tools/my-site/domains','Tên miền','Kết nối, xác minh và xem trạng thái tên miền riêng.'],['/tools/my-site/edit','Dữ liệu & hồ sơ','Chọn khóa học, thành viên liên kết và thông tin website.']].map(([href,title,description])=><a key={href} href={href} className="rounded-2xl border bg-white p-5 hover:border-violet-400"><h2 className="font-bold mb-2">{title} →</h2><p className="text-sm text-slate-600">{description}</p></a>)}</nav>
    {error && <p role="alert" className="p-4 rounded-xl bg-red-50 text-red-700">{error}</p>}{message && <p role="status" className="p-4 rounded-xl bg-green-50 text-green-800">{message}</p>}
    {!data && !error && <p role="status">Đang tải cấu hình…</p>}
    {data && <><div className="flex flex-wrap gap-3">{view && <a className="rounded-lg bg-violet-700 text-white px-4 py-3" href={'https://'+view.hostname} target="_blank" rel="noreferrer">Xem {view.hostname} ↗</a>}<a className="rounded-lg border px-4 py-3" href={'/page/'+data.slug} target="_blank" rel="noreferrer">Xem trang trên hệ thống ↗</a></div>
    <fieldset disabled={busy} className="bg-white border rounded-2xl p-4 sm:p-6 grid gap-5"><legend className="font-bold text-xl px-2">Chức năng website</legend><p className="text-sm text-slate-600">Quyền được cấp và chức năng đang bật là hai thiết lập riêng. Lưu tại đây áp dụng cho mọi tên miền của website này.</p>
      {moduleKeys.map(key=>{const granted=data.access.base[key] || extra[key];return <section key={key} className="border rounded-xl p-4 grid gap-3"><div><h2 className="font-bold">{moduleLabels[key]}</h2><p className="text-sm text-slate-500 mt-1">{data.access.base[key] ? 'Có trong gói cơ bản đã áp dụng' : extra[key] ? 'Được cấp bổ sung' : 'Chưa được cấp'}</p></div><p className="text-sm text-slate-600">{moduleScopes[key]}</p><div className="flex flex-wrap gap-5">{data.admin && <label className="flex items-center gap-2"><input type="checkbox" checked={extra[key]} onChange={e=>setExtra({...extra,[key]:e.target.checked})}/>Cấp bổ sung</label>}<label className="flex items-center gap-2"><input type="checkbox" checked={enabled[key]} disabled={!granted} onChange={e=>setEnabled({...enabled,[key]:e.target.checked})}/>Bật sử dụng</label></div></section>})}
      <button className="justify-self-start rounded-lg bg-violet-700 text-white px-5 py-3" onClick={()=>void save({action:'save',revision:data.access.revision,enabled,...(data.admin ? {extra} : {})})}>{busy ? 'Đang lưu…' : 'Lưu chức năng website'}</button>
    </fieldset>
    {data.admin && <fieldset disabled={busy} className="bg-white border rounded-2xl p-4 sm:p-6 grid gap-4"><legend className="font-bold text-xl px-2">Gói cơ bản · Quản trị viên</legend><p className="text-sm text-slate-600">Trang, menu, tài khoản và giao diện mobile là phần nền tảng. Chọn chức năng bổ sung bên dưới. Lưu mẫu gói không tự thay đổi quyền website đang hoạt động; dùng nút áp dụng để cập nhật website này.</p>{moduleKeys.map(key=><label key={key} className="flex gap-3"><input type="checkbox" checked={basic[key]} onChange={e=>setBasic({...basic,[key]:e.target.checked})}/>{moduleLabels[key]}</label>)}<div className="flex flex-wrap gap-3"><button className="border rounded-lg px-4 py-3" onClick={()=>void save({action:'basic',modules:basic})}>Lưu mẫu gói cơ bản</button><button className="border rounded-lg px-4 py-3" onClick={()=>void save({action:'save',revision:data.access.revision,enabled,extra,applyBasic:true})}>Áp dụng gói đã lưu cho website này</button></div></fieldset>}
    <p className="text-sm text-slate-500">Bản thử hỗ trợ Khóa học, CRM và Affiliate. Email marketing và các tiện ích khác sẽ được bổ sung sau khi tích hợp quyền dữ liệu.</p></>}
  </div></main>
}
